import { useEffect, useRef, useState } from 'react';
import { useSession, downloadFile } from './useSession';
import type { Person, View } from './types';
import { formatTime, isActive, labelAssociation, STATUS } from './types';
import Icon from './Icon';
import MapCanvas from './MapCanvas';
import type { MapTool } from './MapCanvas';
import SetupFlow, { readiness } from './SetupFlow';
import { CameraPanel } from './CameraPanel';
import './aero.css';

function explainError(msg: string): string {
  if (msg.includes('zona de detección es [u, v]')) return `Uno de los puntos de la zona de detección quedó fuera del video (por ejemplo, al marcar justo en el borde de la imagen). Vuelve a "Marcar zona", usa "Deshacer punto" para quitar el último y márcalo de nuevo dentro del video.\n${msg}`;
  if (msg.includes('Correspondencias inconsistentes')) return `Los puntos de calibración no coinciden bien entre el video y el plano — probablemente están muy juntos o casi en línea recta. Bórralos con "Reiniciar calibración" y vuelve a marcar 6 a 8 puntos repartidos por toda el área visible.\n${msg}`;
  if (msg.includes('heading fuera de rango')) return `La dirección de la cámara quedó fuera de 0°-360°. Corrígela en "Configurar cámara", campo "Dirección de visión".\n${msg}`;
  if (msg.includes('Calibración degenerada')) return `Los puntos de calibración marcados están alineados o repetidos y no permiten calcular la posición real. Marca puntos que no estén todos sobre la misma línea.\n${msg}`;
  return msg;
}
const NAV: {id:View;label:string;icon:string}[] = [{id:'overview',label:'Vista general',icon:'grid'},{id:'setup',label:'Configuración',icon:'settings'},{id:'map',label:'Plano vivo',icon:'map'},{id:'cameras',label:'Cámaras',icon:'camera'},{id:'lab',label:'Laboratorio',icon:'lab'},{id:'dashboard',label:'Dashboard',icon:'chart'},{id:'zones',label:'Zonas ROI',icon:'pin'},{id:'rules',label:'Reglas',icon:'alert'},{id:'reports',label:'Reportes',icon:'report'},{id:'audit',label:'Auditoría',icon:'shield'}];

function PanelHeader({number,title,color='blue',children}:{number?:number;title:string;color?:string;children?:React.ReactNode}) {
  return <div className="panel-heading"><div>{number&&<span className={`panel-number ${color}`}>{number}</span>}<h2>{title}</h2></div>{children}</div>;
}
function Metric({label,value,icon,note,tone='blue'}:{label:string;value:string|number;icon:string;note?:string;tone?:string}) {
  return <article className="metric-card"><Icon name={icon} size={25}/><div><span>{label}</span><strong className={`text-${tone}`}>{value}</strong>{note&&<small>{note}</small>}</div></article>;
}

export default function AeroTrack() {
  const session=useSession();
  const {config,state}=session;
  const initial=new URLSearchParams(location.search).get('view') as View;
  const [view,setView]=useState<View>(NAV.some(n=>n.id===initial)?initial:'overview');
  const [selected,setSelected]=useState('');
  const [person,setPerson]=useState<Person|null>(null);
  const mapRef=useRef<HTMLElement>(null);
  const [step,setStep]=useState(0);
  const [detector,setDetector]=useState('yolo');
  const [weights,setWeights]=useState('');
  const [tool,setTool]=useState<MapTool>('select');
  const [clock,setClock]=useState(new Date());
  const [reportKind,setReportKind]=useState('zones');
  useEffect(()=>{const id=setInterval(()=>setClock(new Date()),1000);return()=>clearInterval(id);},[]);
  useEffect(()=>{if(config&&!config.cameras.some(c=>c.id===selected))setSelected(config.cameras[0]?.id||'');},[config,selected]);
  useEffect(()=>{if(!['running','paused'].includes(state.status))setPerson(null);},[state.status]);
  function navigate(next:View) {setView(next);history.replaceState(null,'',`?view=${next}`);}
  if(!config)return <div className="aero connection-screen"><div className="aero-logo"><Icon name="plane" size={38}/><strong>AeroTrack</strong></div><div className="connection-card"><span className="loader"/><h1>Conectando con el centro de monitoreo</h1><p>Inicia el servidor local para acceder al plano y las cámaras.</p><code>python live_server.py</code><small>Backend local · puerto 8765</small></div></div>;
  const busy=isActive(state.status);
  const current=session.connected&&['running','paused'].includes(state.status);
  const people=current?state.people:[];
  const observed=new Set(people.map(p=>p.id)).size;
  const alerts=current?state.analytics.clusters.filter(c=>c.alert).length+state.analytics.zones.filter(z=>z.alert).length:0;
  const activeCameras=current?state.cameras.filter(c=>c.status==='live').length:0;
  const camera=config.cameras.find(c=>c.id===selected);
  const stages=readiness(config,session);
  const ready=stages.every(s=>s.done);
  const demo=state.mode==='demo';
  function save() {void session.action(async()=>{await session.save();session.setNotice('Configuración guardada.');});}
  function start(id?:string, mode=detector) {void session.action(async()=>{await session.save();await session.post('start',{detector:mode,camera:id||null,weights,requireUnified:!id});session.setNotice(mode==='demo'?'Demostración sintética iniciada.':'Procesamiento iniciado. La precisión del detector debe evaluarse con datos anotados.');});}
  const openCameraSettings=()=>{setStep(1);navigate('setup');};
  const cameraPanel=(laboratory=false)=><CameraPanel session={session} selected={selected} onSelected={setSelected} detector={detector} onDetector={setDetector} weights={weights} onWeights={setWeights} laboratory={laboratory} onStart={()=>start(selected)} onConfigure={openCameraSettings}/>;
  function report(format:string) {void session.action(async()=>{const response=await fetch(`/api/report?format=${format}&kind=${reportKind}`);if(!response.ok){const e=await response.json();throw new Error(e.error||'No se pudo exportar el reporte');}downloadFile(`aerotrack-${reportKind}.${format}`,await response.blob());session.setNotice('Reporte exportado con los datos disponibles de esta sesión.');});}
  const stats=<div className="metrics-row"><Metric label="Personas observadas" value={observed} icon="people" note="IDs de la sesión actual"/><Metric label="Aglomeraciones" value={alerts} icon="alert" tone={alerts?'red':'green'} note={`≥ ${config.minPeople} personas · ${config.dwell}s`}/><Metric label="Cámaras activas" value={`${activeCameras} / ${config.cameras.length}`} icon="camera" note={config.clocksVerified?'Sincronización declarada':'Sincronización por verificar'}/><Metric label="Tiempo de fuente" value={formatTime(state.t)} icon="clock" note={state.processingMs?`${state.processingMs} ms por ciclo`:'Esperando procesamiento'}/></div>;
  const executive=(compact=false)=><div className={`executive ${compact?'compact':''}`}><div className="executive-metrics"><Metric label="IDs analizados en sesión" value={state.totals?.identities||0} icon="people" note="Estimación, no conteo validado"/><Metric label="Tiempo observado medio" value={`${(state.totals?.meanObservedSeconds||0).toFixed(1)} s`} icon="clock"/><Metric label="Zonas analizadas" value={state.analytics.zones.length||state.analytics.heat.length} icon="pin" tone="green"/><Metric label="Episodios de alerta" value={state.totals?.alerts||0} icon="alert" tone="red"/></div><div className="executive-grid"><div className="rankings"><h3>Zonas por ocupación acumulada</h3><small>Personas × tiempo observado</small>{state.analytics.heat.length?state.analytics.heat.slice(0,5).map((cell,i)=><div className="rank-row" key={i}><span>Sector {i+1} <small>({cell.x.toFixed(1)}, {cell.y.toFixed(1)})</small></span><div><i style={{width:`${Math.max(2,cell.seconds/Math.max(1,state.analytics.heat[0].seconds)*100)}%`}}/><b>{cell.seconds.toFixed(1)}</b></div></div>):<div className="inline-empty"><Icon name="chart" size={28}/><p>Las zonas aparecerán cuando se registren posiciones en el plano.</p></div>}</div><div className="business-map"><h3>Mapa de calor de ocupación</h3><MapCanvas compact config={config} state={state} connected={session.connected} selectedCamera={selected} onCamera={setSelected} onPerson={setPerson}/></div><aside className="business-note"><Icon name="shield" size={25}/><h3>Información para decidir</h3><p>Las áreas con mayor paso y permanencia son candidatas para estudiar nuevos servicios o comercios.</p><ul><li>Tracking anónimo activo durante la sesión.</li><li>Sin identificación personal.</li><li>IDs y recorridos eliminados al finalizar.</li><li>El análisis no estima rentabilidad.</li></ul><button onClick={()=>navigate('reports')}><Icon name="download" size={16}/> Exportar reporte</button></aside></div></div>;
  return <div className="aero"><header className="aero-header"><div className="aero-logo"><Icon name="plane" size={31}/><strong>AeroTrack</strong></div><div className="aero-title"><h1>Monitoreo de aglomeraciones y tracking anónimo</h1><p>{config.airport||'Aeropuerto'} · {config.floor||'Espacio principal'}</p></div><div className="header-indicators"><span><Icon name="clock" size={15}/> {session.connected?STATUS[state.status]:'Sin conexión'}</span><span><Icon name="shield" size={15}/> Datos anónimos</span><span className="operator"><Icon name="user" size={15}/> Administrador local</span></div></header>
    <nav className="aero-nav">{NAV.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>navigate(n.id)}><Icon name={n.icon} size={16}/>{n.label}</button>)}<button className="popout" title="Abrir otra vista en ventana" onClick={()=>window.open(`/?view=${view==='lab'?'map':'lab'}`,`aerotrack-${view==='lab'?'map':'lab'}`,'width=1450,height=950')}><Icon name="expand" size={17}/></button></nav>
    <main className="aero-main">
      {(!session.connected||session.error||state.error)&&<div className="notice error" role="alert"><Icon name="alert"/><span>{explainError(session.error||state.error||'Backend desconectado. Las posiciones no se presentan como actuales.')}</span>{session.error&&<button onClick={()=>session.setError('')}>Cerrar</button>}</div>}
      {session.notice&&<div className="notice" role="status"><Icon name="check"/><span>{session.notice}</span><button onClick={()=>session.setNotice('')}>×</button></div>}
      {demo&&<div className="notice warning"><Icon name="lab"/><span>SIMULACIÓN · Datos sintéticos para probar las pantallas. No representan mediciones de un aeropuerto.</span></div>}
      {view!=='setup'&&!ready&&<div className="setup-banner"><div><Icon name="settings" size={21}/><span><strong>Configura tu espacio paso a paso</strong><small>{stages.filter(s=>s.done).length}/5 pasos preparados · {stages.filter(s=>!s.done).map(s=>s.title.toLowerCase()).join(', ')} pendientes</small></span></div><button onClick={()=>{setStep(Math.max(0,stages.findIndex(s=>!s.done)));navigate('setup');}}>Continuar configuración <Icon name="arrow" size={15}/></button></div>}
      <div className="session-bar"><div className="inline"><i className={`dot ${state.status==='running'?'green':state.status==='error'?'red':'amber'}`}/><strong>{state.session?`Sesión ${state.session}`:'Sin sesión activa'}</strong><span>{config.sourceMode==='live'?'Cámaras en vivo':config.sourceMode==='demo'?'Demostración':'Grabaciones de prueba'}</span>{session.dirty&&<span className="unsaved">Cambios sin guardar</span>}</div><div className="inline"><time>{clock.toLocaleTimeString('es-PE',{timeZone:'America/Lima'})}</time>{busy?<>{state.status==='paused'?<button onClick={()=>void session.action(async()=>{await session.post('resume',{});})}>▶ Reanudar</button>:<button disabled={state.status!=='running'} onClick={()=>void session.action(async()=>{await session.post('pause',{});})}>Ⅱ Pausar</button>}<button className="danger" disabled={session.busy||state.status==='stopping'} onClick={()=>void session.action(async()=>{await session.post('stop',{});})}>Finalizar sesión</button></>:<><button disabled={session.busy||!config.cameras.length} onClick={()=>start(undefined,'demo')}>Ver simulación</button><button className="primary" disabled={session.busy||!session.connected||!config.cameras.length} onClick={()=>start(undefined,config.sourceMode==='demo'?'demo':detector)}>Iniciar {config.cameras.length} cámara{config.cameras.length===1?'':'s'}</button></>}</div></div>
      {view==='setup'?<SetupFlow session={session} selected={selected} onSelected={setSelected} onNavigate={navigate} step={step} setStep={setStep} startTest={()=>{start(selected);navigate('lab');}}/>:<>
      {view==='overview'&&<><div className="overview-grid"><section className="aero-panel"><PanelHeader number={1} title="Configuración de plano y cámaras"><button disabled={busy} onClick={()=>{setStep(2);navigate('setup');}}>Editar plano <Icon name="arrow" size={14}/></button></PanelHeader><div className="overview-plan"><aside><button onClick={()=>{setStep(2);navigate('setup');}}><Icon name="upload" size={14}/> Cargar plano</button><button onClick={()=>{setStep(2);navigate('setup');}}><Icon name="map" size={14}/> Plano en blanco</button><button onClick={()=>{setStep(1);navigate('setup');}}><Icon name="camera" size={14}/> Cámaras ({config.cameras.length})</button><button onClick={()=>navigate('zones')}><Icon name="pin" size={14}/> Zonas ROI</button><button onClick={()=>navigate('rules')}><Icon name="alert" size={14}/> Reglas</button><button onClick={()=>{setStep(1);navigate('setup');}}><Icon name="link" size={14}/> Vecindad</button></aside><MapCanvas compact config={config} state={{...state,people:[],analytics:{...state.analytics,clusters:[],heat:[]}}} connected={false} selectedCamera={selected} onCamera={setSelected}/></div><div className="panel-footer"><span>Plano editable · unidades {config.unit==='meters'?'métricas':'relativas'}</span><button className="primary" disabled={busy||session.busy} onClick={save}>Guardar</button></div></section><section className="aero-panel"><PanelHeader number={2} title="Vista general del flujo" color="green"><span className={`pill ${current?'good':'muted'}`}>{current?'● '+(demo?'Simulación':'Procesando'):'Sin sesión'}</span></PanelHeader><div className="mini-metrics"><span>IDs únicos estimados <b>{observed}</b></span><span>Aglomeraciones <b className="text-red">{alerts}</b></span><span>Cámaras activas <b>{activeCameras} / {config.cameras.length}</b></span></div><MapCanvas compact config={config} state={state} connected={session.connected} selectedCamera={selected} onCamera={setSelected} onPerson={setPerson}/><div className="panel-footer"><span>{!alerts?'No se detectaron aglomeraciones':`${alerts} áreas requieren revisión`}</span><button className="primary" onClick={()=>navigate('map')}>Abrir plano vivo <Icon name="arrow" size={14}/></button></div></section><section className="aero-panel"><PanelHeader number={3} title="Prueba individual de una cámara" color="amber"><span className="pill muted">LABORATORIO</span></PanelHeader>{cameraPanel(true)}</section><section className="aero-panel"><PanelHeader number={4} title="Video de cámara con tracking" color="purple"><button onClick={()=>navigate('cameras')}>Ampliar <Icon name="expand" size={14}/></button></PanelHeader>{cameraPanel()}</section></div><section className="aero-panel executive-panel"><PanelHeader number={5} title="Dashboard de negocio · análisis ROI" color="red"><button onClick={()=>navigate('dashboard')}>Ver análisis completo <Icon name="arrow" size={14}/></button></PanelHeader>{executive(true)}</section></>}
      {view==='map'&&<>{stats}<section className="aero-panel map-live" ref={mapRef}><PanelHeader title="Plano vivo · posiciones y trayectorias"><span className="pill blue">{config.floor}</span><button title="Pantalla completa" onClick={()=>void mapRef.current?.requestFullscreen().catch(()=>{})}><Icon name="expand" size={15}/></button></PanelHeader><MapCanvas config={config} state={state} connected={session.connected} selectedCamera={selected} onCamera={setSelected} selectedPerson={person?.id} onPerson={setPerson}/></section></>}
      {(view==='cameras'||view==='lab')&&<><div className="page-heading"><div><span className="eyebrow">{view==='lab'?'VALIDACIÓN DE FUENTES':'RED DE CÁMARAS'}</span><h1>{view==='lab'?'Laboratorio de cámaras':'Todas las cámaras, una sesión'}</h1><p>{view==='lab'?'Prueba cada fuente antes de integrarla al sistema.':'Selecciona una cámara para inspeccionar el video y sus IDs temporales.'}</p></div><button disabled={busy} onClick={openCameraSettings}><Icon name="plus"/> Añadir o configurar cámaras</button></div><div className="camera-selector-grid">{config.cameras.map(c=><button key={c.id} className={c.id===selected?'selected':''} onClick={()=>setSelected(c.id)}><Icon name="camera" size={25}/><span><strong>{c.name||c.id}</strong><small>{c.id} · {c.location||'Ubicación pendiente'}</small></span><i className={`dot ${state.cameras.find(s=>s.id===c.id)?.status==='live'&&current?'green':'amber'}`}/></button>)}</div><section className="aero-panel camera-full"><PanelHeader title={`${selected||'Cámara'} · ${camera?.name||'Fuente de video'}`}><span className="pill muted">Sin identificación personal</span></PanelHeader>{cameraPanel(view==='lab')}</section>{view==='lab'&&<div className="lab-guidance"><div><Icon name="check"/><h3>Fuente y rendimiento</h3><p>Comprueba señal, resolución y tiempo de procesamiento. Los FPS de la fuente no son los FPS de inferencia.</p></div><div><Icon name="pin"/><h3>Calidad de calibración</h3><p>Usa referencias distribuidas en el suelo y comprueba el error con puntos adicionales.</p><button onClick={()=>{setStep(3);navigate('setup');}}>Calibrar esta cámara</button></div><div><Icon name="people"/><h3>Estabilidad del tracking</h3><p>Revisa cambios de ID y fragmentaciones contra anotaciones. La continuidad aparente no demuestra precisión.</p></div></div>}</>}
      {view==='dashboard'&&<><div className="page-heading"><div><span className="eyebrow">INTELIGENCIA DEL ESPACIO</span><h1>Dashboard ejecutivo</h1><p>Flujo, ocupación y oportunidades de mejora durante la sesión.</p></div><button className="primary" onClick={()=>navigate('reports')}><Icon name="download"/> Exportar análisis</button></div><section className="aero-panel">{executive()}</section><section className="aero-panel trend-panel"><PanelHeader title="Evolución de personas observadas"/><div className="trend-chart">{state.series?.length?<svg viewBox="0 0 1000 180" role="img" aria-label="Personas observadas a lo largo del tiempo de fuente"><path d="M20 10V155H980" stroke="#395465" fill="none"/>{[0,1,2,3].map(i=><path key={i} d={`M20 ${20+i*40}H980`} stroke="#213745" strokeDasharray="3 5"/>)}<polyline points={state.series.map((s,i)=>`${20+i/Math.max(1,state.series!.length-1)*950},${150-s.count/Math.max(1,...state.series!.map(x=>x.count))*125}`).join(' ')} fill="none" stroke="#159cff" strokeWidth="2.5"/><text x="20" y="174" fill="#8ba8bb" fontSize="11">{formatTime(state.series[0].t)}</text><text x="930" y="174" fill="#8ba8bb" fontSize="11">{formatTime(state.t)}</text></svg>:<div className="inline-empty">El gráfico aparecerá al iniciar una sesión.</div>}</div></section></>}
      {view==='zones'&&<><div className="page-heading"><div><span className="eyebrow">GESTIÓN DEL ESPACIO</span><h1>Zonas de interés y áreas operativas</h1><p>Dibuja áreas, clasifica su uso o incorpora sectores sugeridos por ocupación.</p></div><button className="primary" disabled={busy||session.busy} onClick={save}>Guardar zonas</button></div><div className="zones-grid"><section className="aero-panel"><MapCanvas config={config} state={state} connected={session.connected} selectedCamera={selected} onCamera={setSelected} editable={!busy} onChange={session.setConfig} tool={tool} onTool={setTool}/></section><section className="aero-panel zone-list"><PanelHeader title="Áreas registradas"/>{config.zones.map((z,i)=><div className="zone-item" key={z.id||i}><input aria-label={`Nombre de zona ${i+1}`} disabled={busy} value={z.name} onChange={e=>session.setConfig({...config,zones:config.zones.map((x,j)=>i===j?{...x,name:e.target.value}:x)})}/><select aria-label={`Tipo de zona ${i+1}`} disabled={busy} value={z.kind||'roi'} onChange={e=>session.setConfig({...config,zones:config.zones.map((x,j)=>i===j?{...x,kind:e.target.value as typeof x.kind}:x)})}>{Object.entries({roi:'ROI',commercial:'Comercio',queue:'Cola',restricted:'Restringida',room:'Sala',corridor:'Pasillo',wall:'Muro',door:'Puerta'}).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button title={`Eliminar ${z.name}`} disabled={busy} onClick={()=>session.setConfig({...config,zones:config.zones.filter((_,j)=>j!==i)})}><Icon name="trash" size={15}/></button></div>)}{!config.zones.length&&<p className="empty-text">No hay zonas dibujadas. Crea un polígono, rectángulo o círculo en el plano.</p>}<h3>Sectores sugeridos</h3>{state.analytics.heat.slice(0,5).map((cell,i)=><div className="suggestion" key={i}><div><strong>Sector {i+1}</strong><small>{cell.seconds.toFixed(1)} pers·s · pico {cell.peak}</small></div><button disabled={busy} onClick={()=>{const x=Math.min(cell.x,config.width-cell.size),y=Math.min(cell.y,config.height-cell.size),s=cell.size;session.setConfig({...config,zones:[...config.zones,{id:crypto.randomUUID(),name:`ROI sugerida ${config.zones.length+1}`,kind:'roi',shape:'rectangle',points:[[x,y],[x+s,y],[x+s,y+s],[x,y+s]]}]});}}>Añadir ROI</button></div>)}<p className="subtle">Sugerencia basada en ocupación observada; requiere evaluación operativa y comercial.</p></section></div></>}
      {view==='rules'&&<><div className="page-heading"><div><span className="eyebrow">ALERTAS CONFIGURABLES</span><h1>Reglas de aglomeración</h1><p>Ajusta cantidad, cercanía y permanencia. Las reglas globales se pueden aplicar durante el procesamiento.</p></div></div><section className="aero-panel rules-panel"><PanelHeader title="Agrupaciones automáticas"/><div className="rules-form"><label>Radio ({config.unit==='meters'?'metros':'unidades relativas'})<input type="number" min="0.01" step="0.1" value={config.radius} onChange={e=>session.setConfig({...config,radius:+e.target.value})}/></label><label>Personas mínimas<input type="number" min="2" step="1" value={config.minPeople} onChange={e=>session.setConfig({...config,minPeople:+e.target.value})}/></label><label>Permanencia (segundos)<input type="number" min="0" value={config.dwell} onChange={e=>session.setConfig({...config,dwell:+e.target.value})}/></label><button className="primary" disabled={session.busy} onClick={()=>void session.action(async()=>{if(busy)await session.post('settings',{radius:config.radius,minPeople:config.minPeople,dwell:config.dwell});else await session.save();session.setNotice('Reglas aplicadas.');})}>Aplicar reglas</button></div><p className="subtle">Una fila y una aglomeración pueden parecerse geométricamente. Define límites apropiados al uso de cada zona.</p></section><section className="aero-panel zone-rules"><PanelHeader title="Reglas por zona"/>{config.zones.filter(z=>!['wall','door'].includes(z.kind||'')).map(z=>{const index=config.zones.indexOf(z);const rule=z.rule||{enabled:false,minPeople:config.minPeople,dwell:config.dwell};const update=(patch:Partial<typeof rule>)=>session.setConfig({...config,zones:config.zones.map((v,i)=>i===index?{...v,rule:{...rule,...patch}}:v)});return <div className="zone-rule" key={index}><label className="check"><input type="checkbox" disabled={busy} checked={rule.enabled} onChange={e=>update({enabled:e.target.checked})}/>{z.name}</label><label>Personas<input type="number" disabled={busy} min="2" value={rule.minPeople} onChange={e=>update({minPeople:+e.target.value})}/></label><label>Segundos<input type="number" disabled={busy} min="0" value={rule.dwell} onChange={e=>update({dwell:+e.target.value})}/></label></div>})}{!config.zones.length&&<p className="empty-text">Dibuja una zona para asignarle una regla particular.</p>}<button disabled={busy||session.busy} onClick={save}>Guardar reglas por zona</button></section></>}
      {view==='reports'&&<><div className="page-heading"><div><span className="eyebrow">REPORTES DE SESIÓN</span><h1>Información para tu empresa</h1><p>Exporta los datos disponibles, su procedencia y sus unidades. Los datos sintéticos se identifican como demostración.</p></div></div><section className="aero-panel reports-panel"><div className="report-tabs">{Object.entries({zones:'Zonas calientes',flow:'Flujo horario',occupancy:'Ocupación',trajectories:'Trayectorias',comparison:'Comparativas'}).map(([key,label])=><button key={key} className={reportKind===key?'selected':''} onClick={()=>setReportKind(key)}>{label}</button>)}</div><div className="report-summary"><Icon name="report" size={36}/><div><h2>{({zones:'Zonas de mayor ocupación',flow:'Evolución del flujo',occupancy:'Ocupación por zona',trajectories:'Recorridos de la sesión activa',comparison:'Comparación entre zonas'})[reportKind]}</h2><p>{reportKind==='trajectories'?'Los IDs y recorridos están disponibles solo durante la sesión activa.':'Los valores provienen de observaciones procesadas; no se rellenan métricas sin datos.'}</p><span className="pill muted">{state.session?`Sesión ${state.session}`:'Sin sesión'} · {demo?'Sintético':'Fuente real'} · {config.unit==='meters'?'Metros':'Unidades relativas'}</span></div></div><div className="export-buttons"><button className="primary" disabled={session.busy||!state.session} onClick={()=>report('pdf')}><Icon name="download"/> PDF</button><button disabled={session.busy||!state.session} onClick={()=>report('xlsx')}><Icon name="download"/> Excel</button><button disabled={session.busy||!state.session} onClick={()=>report('csv')}><Icon name="download"/> CSV</button><button disabled={!state.session} onClick={()=>downloadFile('aerotrack-resumen.json',JSON.stringify({session:state.session,mode:state.mode,unit:config.unit,totals:state.totals,analytics:state.analytics},null,2))}>JSON</button></div><table><thead><tr><th>Zona / sector</th><th>Personas × segundos</th><th>Pico observado</th><th>Prioridad de revisión</th></tr></thead><tbody>{state.analytics.heat.slice(0,12).map((c,i)=><tr key={i}><td>Sector ({c.x.toFixed(2)}, {c.y.toFixed(2)})</td><td>{c.seconds.toFixed(1)}</td><td>{c.peak}</td><td>{i+1}</td></tr>)}</tbody></table>{!state.analytics.heat.length&&<p className="empty-text">Aún no hay ocupación registrada. Procesa una fuente calibrada o prueba la demostración.</p>}</section></>}
      {view==='audit'&&<><div className="page-heading"><div><span className="eyebrow">TRAZABILIDAD OPERATIVA</span><h1>Auditoría del sistema</h1><p>Acciones del operador durante la ejecución del servidor. No contiene identidades reales.</p></div></div><section className="aero-panel audit-panel"><table><thead><tr><th>Fecha y hora</th><th>Acción</th><th>Detalle</th></tr></thead><tbody>{state.audit?.map((event,i)=><tr key={i}><td>{new Date(event.at).toLocaleString('es-PE',{timeZone:'America/Lima'})}</td><td>{event.action}</td><td>{event.detail}</td></tr>)}</tbody></table>{!state.audit?.length&&<p className="empty-text">Las acciones aparecerán al guardar la configuración o iniciar una sesión.</p>}</section></>}
      </>}
      {person&&current&&<aside className="person-drawer"><button className="close-drawer" title="Cerrar recorrido" onClick={()=>setPerson(null)}>×</button><span className="eyebrow">RECORRIDO ANÓNIMO</span><h2>{person.id}</h2><span className={`pill ${person.association==='uncertain'?'warn':'blue'}`}>{labelAssociation(person)}</span><dl><div><dt>Cámara actual</dt><dd>{person.camera}</dd></div><div><dt>Posición observada</dt><dd>{person.point?.map(v=>v.toFixed(2)).join(', ')||'Sin calibración'}</dd></div><div><dt>Próxima cámara probable</dt><dd>{person.nextCamera||'Sin evidencia suficiente'}</dd></div></dl><p>La dirección futura es una estimación. No confirma la identidad en una zona sin cobertura.</p><div className="journey">{state.events.filter(e=>e.id===person.id).slice().reverse().map((e,i)=><div key={i}><span>{formatTime(e.t)}</span><b>{e.from} → {e.to}</b><small>Asociación estimada</small></div>)}</div><button onClick={()=>{setSelected(person.camera);navigate('cameras');setPerson(null);}}>Ver cámara <Icon name="arrow" size={14}/></button></aside>}
    </main><footer className="aero-footer"><span>AeroTrack v0.2 · Monitoreo de flujo y análisis del espacio</span><span><Icon name="shield" size={13}/> Sin identificación personal · IDs eliminados al finalizar sesión</span><span>{session.connected?'● Servidor local conectado':'○ Servidor desconectado'}</span></footer>
  </div>;
}
