import { useEffect, useRef, useState } from 'react';
import type { Camera, Config, Point, SessionState } from './types';
import { isActive, isStream, labelAssociation, STATUS } from './types';
import type { Session } from './useSession';
import Icon from './Icon';

export function CameraVideo({ camera, state, connected, onPoint, mode, pending, zonePoints }: { camera?: Camera; state: SessionState; connected: boolean; onPoint?: (p: Point) => void; mode?: 'calibration' | 'zone'; pending?: Point | null; zonePoints?: Point[] }) {
  const [tick, setTick] = useState(0);
  const [failed, setFailed] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const status = state.cameras.find(c => c.id === camera?.id);
  useEffect(()=>{ setFailed(false); setTick(Date.now()); },[camera?.id,state.session]);
  useEffect(()=>{if(state.status!=='running'||mode||!connected)return; const id=setInterval(()=>{setTick(Date.now());setFailed(false);},800);return()=>clearInterval(id);},[state.status,mode,connected]);
  const available = state.mode !== 'demo' && status && ['live','paused','stopped','ended'].includes(status.status);
  const current = connected && state.status==='running' && status?.status==='live';
  const aspect = status?.width && status?.height ? `${status.width} / ${status.height}` : undefined;
  const drawnZone = zonePoints && zonePoints.length > 0 ? zonePoints : (mode !== 'zone' ? camera?.detectionZone : undefined);
  return <div className="camera-video" ref={ref}>
    {available && !failed ? <img src={`/api/frame?camera=${encodeURIComponent(camera?.id||'')}&v=${tick}`} alt={`Video anonimizado ${camera?.name||camera?.id}`} onError={()=>setFailed(true)} style={aspect?{aspectRatio:aspect}:undefined} className={mode?'calibration-cursor':''} onClick={e=>{if(!mode||!onPoint)return;const r=e.currentTarget.getBoundingClientRect();onPoint([(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height]);}}/> : <div className="video-empty"><Icon name="camera" size={38}/><strong>{!camera?'Añade una cámara':state.mode==='demo'?'Simulación de nodos':status?.status==='error'?'Cámara sin señal':state.status==='starting'?'Conectando con la fuente':'Vista de cámara'}</strong><span>{status?.error || (state.mode==='demo'?'No contiene grabación de personas. Prueba una fuente para ver video.':'Al iniciar una prueba verás el video procesado y los IDs temporales.')}</span></div>}
    <div className="video-top"><span>{camera?.id||'SIN CÁMARA'}{camera?.location?` · ${camera.location}`:''}</span><span className={`pill ${current?'good':'muted'}`}>{current?'● Procesando':state.status==='paused'?'Ⅱ Pausado':available?'Imagen retenida':'Sin señal'}</span></div>
    {pending && mode==='calibration' && <span className="calibration-marker" style={{left:`${pending[0]*100}%`,top:`${pending[1]*100}%`}}/>}
    {drawnZone && drawnZone.length>0 && <svg className="zone-overlay" viewBox="0 0 100 100" preserveAspectRatio="none">
      {drawnZone.length>1 && <polygon points={drawnZone.map(p=>`${p[0]*100},${p[1]*100}`).join(' ')}/>}
      {drawnZone.map((p,i)=><circle key={i} cx={p[0]*100} cy={p[1]*100} r="0.9"/>)}
    </svg>}
    <div className="video-bottom"><span><Icon name="shield" size={13}/> Solo operador · servidor local</span><span>{status?.width?`${status.width} × ${status.height}`:'—'} · {status?.fps?`${status.fps.toFixed(1)} FPS fuente`:'FPS no disponible'}</span><button title="Pantalla completa" onClick={()=>void ref.current?.requestFullscreen().catch(()=>{})}><Icon name="expand" size={15}/></button></div>
  </div>;
}

export function CameraEditor({ config, camera, onChange, session }: { config: Config; camera?: Camera; onChange: (c: Config) => void; session: Session }) {
  const fileRef=useRef<HTMLInputElement>(null);
  if(!camera)return <p className="empty-text">Añade una cámara para configurar su fuente.</p>;
  const disabled=isActive(session.state.status);
  function update(patch: Partial<Camera>) { onChange({...config,cameras:config.cameras.map(c=>c.id===camera!.id?{...c,...patch}:c)}); }
  return <div className="camera-editor"><div className="form-grid"><label>Nombre<input disabled={disabled} value={camera.name||camera.id} maxLength={80} onChange={e=>update({name:e.target.value})}/></label><label>Ubicación<input disabled={disabled} value={camera.location||''} placeholder="Terminal A / Piso 1" onChange={e=>update({location:e.target.value})}/></label><label>Tipo<select disabled={disabled} value={camera.type||'tilted'} onChange={e=>update({type:e.target.value as Camera['type']})}><option value="fixed">Fija</option><option value="overhead">Cenital</option><option value="tilted">Inclinada</option></select></label><label>Fuente<select disabled={disabled} value={typeof camera.source==='number'?'usb':isStream(camera.source)?'network':'file'} onChange={e=>update({source:e.target.value==='usb'?0:e.target.value==='network'?'rtsp://':'',pairs:[]})}><option value="file">Video grabado</option><option value="usb">Cámara USB</option><option value="network">RTSP / Cámara IP</option></select></label></div>
    <label>{typeof camera.source==='number'?'Índice USB (0 = primera cámara)':'Ruta del video o URL de cámara'}<div className="input-action"><input disabled={disabled} value={camera.source} placeholder="Selecciona un archivo o escribe una ruta local" onChange={e=>update({source:typeof camera.source==='number'?Number(e.target.value):e.target.value,pairs:[]})}/>{!isStream(camera.source)&&<button disabled={disabled||session.busy} title="Subir video" onClick={()=>fileRef.current?.click()}><Icon name="upload" size={16}/></button>}</div></label>
    <input ref={fileRef} hidden type="file" accept="video/*,.mp4,.avi,.mov,.mkv" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void session.action(async()=>{const result=await session.post(`upload?name=${encodeURIComponent(file.name)}`,file,true);update({source:result.path,pairs:[]});session.setNotice('Video cargado. Guarda la cámara para iniciar la prueba.');});}}/>
    <div className="form-grid"><label>Desfase al inicio (segundos)<input disabled={disabled||isStream(camera.source)} type="number" min="0" step="0.1" value={camera.offset} onChange={e=>update({offset:+e.target.value})}/></label><label>Forma del alcance<select disabled={disabled} value={camera.coverageShape??'cone'} onChange={e=>update({coverageShape:e.target.value as Camera['coverageShape']})}><option value="cone">Cono (campo de visión)</option><option value="rectangle">Rectángulo (pasillo/corredor)</option></select></label><label>Dirección de visión (°)<input disabled={disabled} type="number" min="0" max="360" value={Math.round(camera.heading??90)} onChange={e=>update({heading:+e.target.value})}/></label>{camera.coverageShape==='rectangle'?<label>Ancho del rectángulo ({config.unit==='meters'?'m':'u'})<input disabled={disabled} type="number" min="0.2" step="0.1" value={camera.coverageWidth??2} onChange={e=>update({coverageWidth:+e.target.value})}/></label>:<label>Ángulo de visión (°)<input disabled={disabled} type="number" min="5" max="170" value={camera.fov??60} onChange={e=>update({fov:+e.target.value})}/></label>}<label>Alcance orientativo ({config.unit==='meters'?'m':'u'})<input disabled={disabled} type="number" min="0.1" step="0.5" value={Number((camera.range??3).toFixed(2))} onChange={e=>update({range:+e.target.value})}/></label><label>Altura ({config.unit==='meters'?'m':'u'})<input disabled={disabled} type="number" min="0" step="0.1" value={camera.height??3} onChange={e=>update({height:+e.target.value})}/></label><label>Inclinación (°)<input disabled={disabled} type="number" min="0" max="90" value={camera.tilt??45} onChange={e=>update({tilt:+e.target.value})}/></label></div>
    <fieldset disabled={disabled}><legend>Cámaras vecinas · direcciones permitidas</legend>{config.cameras.filter(c=>c.id!==camera.id).map(c=><label className="check" key={c.id}><input type="checkbox" checked={camera.links.includes(c.id)} onChange={e=>update({links:e.target.checked?[...camera.links,c.id]:camera.links.filter(id=>id!==c.id)})}/>{c.id} · {c.name||'Cámara'}</label>)}{config.cameras.length<2&&<p className="subtle">Agrega otra cámara para definir transiciones.</p>}</fieldset>
    <p className="subtle">La cobertura dibujada es orientativa. Selecciona esta cámara en el plano y arrastra el punto ámbar al final de su alcance para reorientarlo o alargarlo directamente. Para ubicar personas necesitas calibrar puntos del suelo. El índice USB pertenece al equipo que ejecuta el servidor.</p>
  </div>;
}

export function CameraPanel({ session, selected, onSelected, detector, onDetector, weights, onWeights, laboratory, onStart, onConfigure, onPoint, pending, mode }: {
  session: Session; selected: string; onSelected:(s:string)=>void; detector:string;onDetector:(s:string)=>void;weights:string;onWeights:(s:string)=>void;
  laboratory?:boolean;onStart:()=>void;onConfigure:()=>void;onPoint?:(p:Point)=>void;pending?:Point|null;mode?:'calibration'|'zone';
}) {
  const config=session.config!;
  const camera=config.cameras.find(c=>c.id===selected);
  const status=session.state.cameras.find(c=>c.id===selected);
  const people=session.connected&&['running','paused'].includes(session.state.status)?session.state.people.filter(p=>p.camera===selected):[];
  return <div className={`camera-workspace ${laboratory?'laboratory':''}`}><div className="camera-controls"><label>Seleccionar cámara<select value={selected} onChange={e=>onSelected(e.target.value)}>{config.cameras.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name||c.location||'Cámara'}</option>)}</select></label><dl className="technical-list"><div><dt>Estado</dt><dd className={status?.status==='live'?'text-green':''}>{status?STATUS[status.status]||status.status:'Sin probar'}</dd></div><div><dt>Resolución</dt><dd>{status?.width?`${status.width} × ${status.height}`:'—'}</dd></div><div><dt>FPS de fuente</dt><dd>{status?.fps?.toFixed(1)||'—'}</dd></div><div><dt>Procesamiento</dt><dd>{status?.processingMs?`${status.processingMs} ms`:session.state.processingMs?`${session.state.processingMs} ms/ciclo`:'—'}</dd></div><div><dt>Calibración</dt><dd>{camera?.pairs.length&&camera.pairs.length>=4?'Referencias guardadas':'Pendiente'}</dd></div><div><dt>Sincronización</dt><dd>{config.clocksVerified?'Declarada verificada':'Por verificar'}</dd></div></dl>
    {laboratory&&<><label>Detector<select disabled={isActive(session.state.status)} value={detector} onChange={e=>onDetector(e.target.value)}><option value="hog">OpenCV HOG · referencia</option><option value="p2pnet">P2PNet · cabezas</option><option value="yolo">YOLO · pesos locales</option></select></label>{detector==='yolo'&&<label>Ruta de pesos<input disabled={isActive(session.state.status)} value={weights} onChange={e=>onWeights(e.target.value)} placeholder="Vacío: usar YOLO11n instalado"/></label>}<button className="primary" disabled={isActive(session.state.status)||session.busy||!camera} onClick={onStart}><Icon name="lab" size={15}/> Iniciar prueba</button><div className="small-note"><Icon name="shield" size={15}/><div><strong>Modo laboratorio</strong><p>Procesa esta cámara para verificar su fuente y calibración antes de incorporarla al plano.</p></div></div></>}
    <button onClick={onConfigure}><Icon name="settings" size={14}/> Configurar cámara</button>
  </div><div className="camera-feed"><CameraVideo camera={camera} state={session.state} connected={session.connected} onPoint={onPoint} pending={pending} mode={mode}/><div className="feed-metrics"><span>Personas detectadas: <b>{people.length}</b></span><span>IDs temporales <i className="signal-bars">▥▥▥▥▥</i></span></div>{!laboratory&&<div className="tracking-chips">{people.slice(0,8).map(p=><span key={p.id} title={labelAssociation(p)} className={p.association==='uncertain'?'uncertain':''}>{p.id}{p.association==='estimated'?' ~':p.association==='uncertain'?' ?':''}</span>)}{!people.length&&<span>Esperando observaciones de esta cámara</span>}</div>}</div></div>;
}
