import {useRef,useState} from 'react';
import type {Camera,Config,Point} from './types';
import {isActive} from './types';
import type {Session} from './useSession';
import {useBusinesses} from './useBusinesses';
import type {Business} from './useBusinesses';
export default function CameraAccessEditor({camera,config,session,onChange,defaultBusiness,embedded=false}:{camera:Camera;config:Config;session:Session;defaultBusiness?:Business;embedded?:boolean;onChange:(c:Config)=>void}){
 const {items}=useBusinesses(session.projects.active||'');
 const [loaded,setLoaded]=useState(false),[revision,setRevision]=useState(0),[selected,setSelected]=useState(''),[drawing,setDrawing]=useState(false),[first,setFirst]=useState<Point|null>(null),[search,setSearch]=useState('');
 const drag=useRef<'a'|'b'|null>(null);
 const lines=camera.countLines||[],line=lines.find(l=>l.id===selected);
 const disabled=session.busy||isActive(session.state.status);
 const businesses=items.filter(b=>b.estado!=='cerrado'&&b.ubicacion?.planId===(camera.planId||config.planId||'custom'));
 const update=(next:NonNullable<Camera['countLines']>)=>onChange({...config,cameras:config.cameras.map(c=>c.id===camera.id?{...c,countLines:next}:c)});
 const point=(e:React.PointerEvent<SVGSVGElement>):Point=>{const r=e.currentTarget.getBoundingClientRect();return [Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];};
 return <section className="region-editor"><div className="region-title"><div><h3>Accesos de negocios · opcional</h3><p>Dibuja una línea sobre la puerta y selecciona el negocio. La cámara mantiene su análisis de ocupación y seguimiento.</p></div></div><label className="check"><input type="checkbox" disabled={disabled||!lines.some(l=>l.place)} checked={!!camera.bagSignal} onChange={e=>onChange({...config,cameras:config.cameras.map(c=>c.id===camera.id?{...c,bagSignal:e.target.checked}:c)})}/>Evaluar objetos nuevos al salir (experimental)</label><p>Requiere un acceso vinculado y cuerpos completos. Compara ropa y objetos; muestra las salidas sin correspondencia y no confirma compras.</p><div className="region-actions"><button disabled={disabled||!camera.source} onClick={()=>void session.action(async()=>{await session.post('camera-preview',{camera:camera.id,seconds:0,source:camera.source});setRevision(Date.now());setLoaded(true);})}>Ver primera imagen</button><button disabled={disabled||!loaded||lines.length>=20} onClick={()=>{setDrawing(true);setFirst(null);}}>Añadir línea de acceso</button>{drawing&&<button onClick={()=>{setDrawing(false);setFirst(null);}}>Cancelar dibujo</button>}</div>{drawing&&<p>Marca dos puntos sobre la puerta. Después puedes arrastrar los extremos.</p>}
 {loaded&&<div className="region-image"><img src={`/api/frame?camera=${encodeURIComponent(camera.id)}&v=${revision}`} alt={`Accesos de ${camera.name}`}/><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Editor de líneas de acceso" onPointerDown={e=>{if(disabled)return;const p=point(e);if(drawing){if(!first)setFirst(p);else if(Math.hypot(p[0]-first[0],p[1]-first[1])>=.02){const id=crypto.randomUUID();update([...lines,{id,name:`Acceso ${lines.length+1}`,a:first,b:p,entrySide:1,place:defaultBusiness?.ubicacion?{id:defaultBusiness.id,name:defaultBusiness.nombre,...defaultBusiness.ubicacion}:undefined}]);setSelected(id);setFirst(null);setDrawing(false);}return;}if(line){const endpoint=(['a','b'] as const).find(k=>Math.hypot(line[k][0]-p[0],line[k][1]-p[1])<.04);if(endpoint){drag.current=endpoint;e.currentTarget.setPointerCapture(e.pointerId);}}}} onPointerMove={e=>{if(!drag.current||!line||disabled)return;const p=point(e);update(lines.map(l=>l.id===line.id?{...l,[drag.current!]:p}:l));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>{lines.map(l=><g key={l.id} onPointerDown={()=>setSelected(l.id)}><line x1={l.a[0]*100} y1={l.a[1]*100} x2={l.b[0]*100} y2={l.b[1]*100} stroke={l.id===selected?'#f59e0b':'#06b6d4'} strokeWidth=".8"/>{(['a','b'] as const).map(k=><circle key={k} cx={l[k][0]*100} cy={l[k][1]*100} r="1.5" fill="#fff" stroke="#087fa5" strokeWidth=".6"/>)}</g>)}{first&&<circle cx={first[0]*100} cy={first[1]*100} r="1" fill="#f59e0b"/>}</svg></div>}
 <label>Línea de la cámara<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Seleccionar acceso…</option>{lines.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>{line&&<div className="business-access-editor"><label>Nombre del acceso<input disabled={disabled} value={line.name} onChange={e=>update(lines.map(l=>l.id===line.id?{...l,name:e.target.value}:l))}/></label><label>Buscar negocio<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nombre de tienda"/></label><label>Negocio que mide este acceso<select disabled={disabled} value={line.place?.id||''} onChange={e=>{const b=businesses.find(b=>b.id===e.target.value);update(lines.map(l=>l.id===line.id?{...l,place:b&&b.ubicacion?{id:b.id,name:b.nombre,...b.ubicacion}:undefined}:l));}}><option value="">Sin negocio vinculado</option>{businesses.filter(b=>b.id===line.place?.id||b.nombre.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map(b=><option key={b.id} value={b.id}>{b.nombre}</option>)}</select></label><p>Entrar: cruzar hacia el lado {line.entrySide===1?'izquierdo':'derecho'} al mirar del primer punto al segundo.</p><div className="region-actions"><button disabled={disabled} onClick={()=>update(lines.map(l=>l.id===line.id?{...l,entrySide:-l.entrySide}:l))}>Invertir entrada y salida</button><button disabled={disabled} onClick={()=>{update(lines.filter(l=>l.id!==line.id));setSelected('');}}>Eliminar línea</button></div></div>}
 {!embedded&&<div className="business-save"><span>{lines.length} accesos configurados</span><button className="primary" disabled={disabled} onClick={()=>void session.action(async()=>{await session.save(config);window.dispatchEvent(new Event('aero:businesses'));session.setNotice('Accesos de la cámara guardados.');})}>Guardar accesos de cámara</button></div>}{embedded&&<p>Los cambios de esta puerta se guardan con Guardar negocio, arriba.</p>}</section>;
}
