import {useEffect,useState} from 'react';
import type {Session} from './useSession';
import './commercial-panel.css';
type Row={id:string;name:string;accesses:number;entries:number|null;sales:number|null;forecast:{estimate:number|null;days:number;reason:string;range?:number[]};incidents:{id:string;start:string;duration:number;peak:number;sales:number|null;baseline:number|null;differencePercent:number|null;sampleDays:number;scope:string}[];bags:{exits:number;matched:number;changed:number;unmatched:number;coverage:number|null}};
type Result={date:string;hour:number;dataset:string;businesses:Row[];imports:{id:string;name:string;rows:number;created:string}[]};
const money=(n:number|null)=>n===null?'Sin datos':new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(n);
export default function CommercialPanel({session}:{session:Session}){
 const params=new URLSearchParams(window.location.search);
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const [tab,setTab]=useState('sales'),[dataset,setDataset]=useState(params.get('dataset')==='demo'?'demo':'real'),[date,setDate]=useState(params.get('date')||today),[hour,setHour]=useState(params.has('hour')?Number(params.get('hour')):Number(new Intl.DateTimeFormat('en-GB',{timeZone:'America/Lima',hour:'numeric',hourCycle:'h23'}).format(new Date()))),[data,setData]=useState<Result|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[csv,setCsv]=useState(''),[filename,setFilename]=useState(''),[validation,setValidation]=useState<{rows:number;errors:string[];imported:boolean}|null>(null),[business,setBusiness]=useState('');
 const [recordingDate,setRecordingDate]=useState(session.config?.recordingStartedAt||'');
 useEffect(()=>setRecordingDate(session.config?.recordingStartedAt||''),[session.config?.recordingStartedAt,session.projects.active]);
 const headers={'X-LAP-Session':localStorage.getItem('aero.session')||''};
 async function openSavedTest(){await session.action(async()=>{const r=await fetch('/api/commercial/sample',{headers});const saved=await r.json();if(!r.ok)throw Error(saved.error);setDataset('demo');setDate(saved.date);setHour(saved.hour);setBusiness(saved.businessId||'');setTab('forecast');});}
 const query=`dataset=${dataset}&date=${date}&hour=${hour}`;
 useEffect(()=>{let alive=true;const controller=new AbortController();const load=async()=>{try{const r=await fetch(`/api/commercial?${query}`,{headers,signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error);if(alive){setData(d);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:'No se pudieron cargar los datos.');}};void load();const timer=setInterval(()=>void load(),5000);return()=>{alive=false;controller.abort();clearInterval(timer);};},[query,refresh,session.projects.active]);
 async function download(path:string,name:string){await session.action(async()=>{const r=await fetch(path,{headers});if(!r.ok)throw Error('No se pudo descargar el archivo.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);});}
 async function upload(preview:boolean){await session.action(async()=>{const result=await session.post('commercial/import',{csv,name:filename,dataset,preview,projectId:session.projects.active});setValidation(result);if(result.imported){setRefresh(x=>x+1);setCsv('');session.setNotice('Ventas importadas sin sobrescribir datos existentes.');}});}
 const all=data?.businesses||[],rows=all.filter(r=>(!business||r.id===business)&&(r.entries!==null||r.sales!==null||r.incidents.length||r.bags.exits));
 return <div className="commerce"><div className="page-heading"><div><h1>Ventas y análisis</h1><p>Relaciona las entradas de los negocios con sus ventas y consulta señales experimentales.</p></div><button onClick={()=>void openSavedTest()}>Ver prueba guardada</button><button onClick={()=>void download(`/api/commercial/export?${query}&kind=${tab==='incidents'?'incidents':'summary'}`,'analisis-comercial.csv')}>Exportar CSV</button></div>
 <section className="aero-panel commerce-filters"><label>Origen<select value={dataset} onChange={e=>{setDataset(e.target.value);setValidation(null);}}><option value="real">Datos reales</option><option value="demo">Datos de prueba guardados</option></select></label><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Hora<select value={hour} onChange={e=>setHour(Number(e.target.value))}>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00–{String(h+1).padStart(2,'0')}:00</option>)}</select></label><label>Negocio<select value={business} onChange={e=>setBusiness(e.target.value)}><option value="">Todos los negocios</option>{all.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></section>
 {dataset==='demo'&&<p className="commerce-test" role="status">Datos de prueba: ventas de ejemplo y tráfico de pruebas, separados de la operación real.</p>}
 <nav className="commerce-tabs" aria-label="Análisis comercial">{[['sales','Ventas CSV'],['forecast','Proyección de ventas'],['incidents','Aglomeraciones y ventas'],['bags','Señal de objeto nuevo']].map(([id,label])=><button key={id} aria-pressed={tab===id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {error&&<p role="alert" className="notice warning">{error}</p>}
 {tab==='sales'&&<section className="aero-panel commerce-content"><h2>Importar ventas por hora</h2><p>Un registro por negocio, fecha y hora. Moneda: soles. Usa los identificadores de la plantilla; no los nombres de las tiendas.</p><button onClick={()=>void download('/api/commercial/template','plantilla-ventas.csv')}>Descargar plantilla de negocios</button>{session.auth.rol==='operador'&&<div className="commerce-import"><label>CSV de ventas<input type="file" accept=".csv,text/csv" onChange={e=>{const f=e.target.files?.[0];setValidation(null);setCsv('');if(f){setFilename(f.name);if(f.size>2000000){setValidation({rows:0,errors:['El archivo supera 2 MB.'],imported:false});return;}void f.text().then(setCsv);}}}/></label><button disabled={!csv||session.busy} onClick={()=>void upload(true)}>Validar archivo</button><button className="primary" disabled={!csv||session.busy||!validation||!!validation.errors.length} onClick={()=>void upload(false)}>Importar ventas</button></div>}{validation&&<div role="status" className={validation.errors.length?'notice warning':'notice'}><strong>{validation.imported?'Importación guardada':`${validation.rows} filas revisadas`}</strong>{validation.errors.length?<ul>{validation.errors.map((e,i)=><li key={i}>{e}</li>)}</ul>:<p>Archivo válido. Se guardará en {dataset==='demo'?'datos de prueba':'datos reales'}.</p>}</div>}<h3>Importaciones guardadas</h3>{!data?.imports.length?<p>No hay importaciones para este origen.</p>:<ul>{data.imports.map(i=><li key={i.id}>{i.name} · {i.rows} filas · {new Date(i.created).toLocaleString('es-PE')}</li>)}</ul>}</section>}
 {tab==='forecast'&&<section className="aero-panel commerce-content"><h2>Venta estimada en esta hora</h2><p>Proyección basada en ingresos por entrada de al menos tres días anteriores comparables. No representa ventas confirmadas ni el ticket por compra.</p></section>}
 {tab==='incidents'&&<section className="aero-panel commerce-content"><h2>Incidentes y ventas de su hora</h2><p>Se compara la hora del incidente con la misma hora y día de semana del histórico. Ventas por hora no permiten atribuir ventas a los minutos exactos del incidente. Coincidencia no implica causalidad.</p></section>}
 {tab==='bags'&&<section className="aero-panel commerce-content"><h2>Señal experimental de objeto nuevo</h2><p>Muestra de las sesiones del día seleccionado. El filtro de hora se aplica a ventas y entradas, no a este resumen diario.</p><p>Solo compara salidas con entradas emparejadas con confianza. El detector reconoce carteras, mochilas y maletas; una cartera nueva no demuestra una compra. Actívala en los accesos de la cámara cuando la puerta y los cuerpos se vean completos.</p><p>Se usa detección adicional de objetos y similitud de ropa. No es una reidentificación facial ni un modelo entrenado para bolsas de tienda.</p></section>}
 <section className="aero-panel commerce-content"><h2>Resultados por negocio</h2>{!rows.length?<p>No hay datos para esta fecha, hora y origen. Importa ventas y procesa cámaras con accesos vinculados. Las grabaciones necesitan su fecha y hora de inicio para cruzar datos.</p>:<div className="commerce-table"><table><thead><tr><th>Negocio</th>{tab==='bags'?<><th>Salidas evaluadas</th><th>Emparejadas</th><th>Objeto nuevo</th><th>Sin emparejar</th><th>Cobertura</th></>:<><th>Entradas</th><th>Venta registrada</th><th>Proyección</th><th>Historial</th></>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.accesses} accesos vinculados</small></td>{tab==='bags'?<><td>{r.bags.exits}</td><td>{r.bags.matched}</td><td>{r.bags.changed}</td><td>{r.bags.unmatched}</td><td>{r.bags.coverage===null?'Sin muestra':`${r.bags.coverage}%`}</td></>:<><td>{r.entries??'Sin medición'}</td><td>{money(r.sales)}</td><td>{money(r.forecast.estimate)}{r.forecast.estimate===null&&<small>{r.forecast.reason}</small>}</td><td>{r.forecast.days} días{r.forecast.range&&<small>Rango observado: {r.forecast.range.map(money).join(' – ')}</small>}</td></>}</tr>)}</tbody></table></div>}
 {tab==='incidents'&&rows.map(r=>r.incidents.length>0&&<div className="commerce-incidents" key={r.id}><h3>{r.name}: {r.incidents.length} incidentes en el día</h3>{r.incidents.length<5&&<p>Muestra pequeña: lectura descriptiva, insuficiente para concluir un patrón.</p>}{r.incidents.map(i=><article key={i.id}><strong>{new Date(i.start).toLocaleTimeString('es-PE',{timeZone:'America/Lima'})} · {i.duration.toFixed(0)} s · pico {i.peak} personas</strong><p>Venta de la hora: {money(i.sales)} · Referencia histórica: {money(i.baseline)} · {i.sampleDays} días comparables</p><p>{i.differencePercent===null?'Comparación insuficiente':`Diferencia descriptiva: ${i.differencePercent}%`}. {i.scope}</p></article>)}</div>)}
 </section>
 {session.auth.rol==='operador'&&session.config?.sourceMode==='recordings'&&<section className="aero-panel commerce-content"><h2>Fecha de las grabaciones</h2><p>Indica cuándo comienza la línea de tiempo sincronizada de los videos. No se usará la fecha en que pulsas Iniciar.</p><label>Inicio con zona horaria<input placeholder="2026-09-27T09:00:00-05:00" value={recordingDate} onChange={e=>setRecordingDate(e.target.value)}/></label><button disabled={session.busy} onClick={()=>void session.action(async()=>{const value=recordingDate;if(value&&(!/(Z|[+-]\d\d:\d\d)$/.test(value)||Number.isNaN(Date.parse(value))))throw Error('Usa una fecha válida con zona horaria, por ejemplo 2026-09-27T09:00:00-05:00.');await session.save({...session.config!,recordingStartedAt:value});session.setNotice('Fecha de grabación guardada.');})}>Guardar fecha de grabación</button></section>}
 </div>;
}
