import {useEffect,useState} from 'react';
import type {Config,SessionState} from './types';
import {EMPTY_STATE,isActive,formatTime} from './types';
import type {Session} from './useSession';
import ExecutiveSummary from './ExecutiveSummary';
import MapCanvas from './MapCanvas';
import ReplayWorkspace from './ReplayWorkspace';
import {CameraVideo} from './CameraPanel';

export default function MonitoringWorkspace({session,onSetup,onReplay,active=true}:{active?:boolean;session:Session;onSetup:(id?:string)=>void;onReplay:()=>void}){
  const config=session.config!;
  const [level,setLevel]=useState('lap-3'),[camera,setCamera]=useState('all'),[zone,setZone]=useState('all');
  const [plan,setPlan]=useState<Config|null>(null),[archived,setArchived]=useState<any>(null),[error,setError]=useState(''),[historyLoading,setHistoryLoading]=useState(true);
  const [quality,setQuality]=useState(640),[unified,setUnified]=useState(false),[allLevels,setAllLevels]=useState(true);
  const [trend,setTrend]=useState<{t:number;zones:any[]}[]>([]);
  useEffect(()=>{setTrend([]);},[session.state.session,level]);
  useEffect(()=>{if(session.state.status!=='running')return;const zones=(session.state as any).levelAnalytics?.[level]?.zones||session.state.analytics.zones;setTrend(rows=>rows[rows.length-1]?.t===session.state.t?rows:[...rows.slice(-1799),{t:session.state.t,zones}]);},[session.state.t,session.state.status,level]);
  const busy=isActive(session.state.status);
  useEffect(()=>{let alive=true;const saved=level===(config.planId||'custom')?config:config.plans?.[level];if(saved){setPlan({...config,...saved,planId:level});return;}
    void fetch(`/maps/lap/${level.split('-')[1]}.json`).then(r=>r.json()).then(m=>{if(alive)setPlan({...config,width:m.width,height:m.height,workArea:undefined,background:'',zones:[],mapAsset:`/maps/lap/${m.floor}.json`,floor:m.name,planId:level,mapConfigured:true});}).catch(()=>setError('No se pudo abrir este nivel.'));return()=>{alive=false;};},[config,level]);
  useEffect(()=>{let alive=true;setHistoryLoading(true);void fetch('/api/replay/history').then(r=>r.json()).then(async rows=>{
    const relevant=rows.filter((r:any)=>r.end>0&&['unified','tracking'].includes(r.module)&&r.cameras.some((v:any)=>(v.planId||r.config?.planId||'custom')===level&&config.cameras.some(c=>c.id===v.id)));
    if(!relevant.length){if(alive)setArchived(null);return;}
    const latest:Record<string,any>={},metadata:Record<string,any>={};
    for(const r of relevant)for(const c of r.cameras)if(!latest[c.id]&&r.cameraAnalytics?.[c.id]){latest[c.id]=r.cameraAnalytics[c.id];metadata[c.id]={created:r.created,session:r.session};}
    const response=await fetch(`/api/replay/data?session=${relevant[0].session}`),d=await response.json();
    if(alive)setArchived({...d,cameraAnalytics:Object.keys(latest).length?latest:d.cameraAnalytics,latestByCamera:metadata});
  }).catch(()=>setError('No se pudo recuperar el último análisis.')).finally(()=>{if(alive)setHistoryLoading(false);});return()=>{alive=false;};},[session.state.session,session.state.status,session.state.serverInstance,level]);
  const cameras=config.cameras.filter(c=>(c.planId||'custom')===level&&(camera==='all'||c.id===camera));
  const last=archived?.samples?.at(-1);
  const cameraAnalytics=busy?session.state.cameraAnalytics||{}:archived?.cameraAnalytics||Object.fromEntries((archived?.cameras||[]).map((c:any)=>{const row=[...(archived.samples||[])].reverse().find((r:any)=>r.cameras.some((v:any)=>v.id===c.id));return [c.id,row?.cameras.find((v:any)=>v.id===c.id)?.analysis];}));
  const base:SessionState=busy?session.state:{...EMPTY_STATE,status:'ended',planId:archived?.config?.planId,t:last?.t||0,analytics:last?.analytics||EMPTY_STATE.analytics};
  const levelAnalytics=busy?(session.state as any).levelAnalytics?.[level]:last?.levels?.[level];
  const state={...base,planId:level,people:base.people.filter(p=>cameras.some(c=>c.id===p.camera)),analytics:levelAnalytics||EMPTY_STATE.analytics};
  if(camera!=='all')state.analytics=cameraAnalytics[camera]?.map||{...EMPTY_STATE.analytics,mappedCount:state.people.filter(p=>p.point).length};
  const zoneNames=[...new Set(cameras.flatMap(c=>cameraAnalytics[c.id]?.occupancy?.zones?.map((z:any)=>z.name)||[]))] as string[];
  const entries=cameras.reduce((n,c)=>n+(cameraAnalytics[c.id]?.crossings||[]).reduce((a:number,l:any)=>a+l.entries,0),0);
  const exits=cameras.reduce((n,c)=>n+(cameraAnalytics[c.id]?.crossings||[]).reduce((a:number,l:any)=>a+l.exits,0),0);
  return <div className="monitoring-workspace"><div className="page-heading"><div><span className="eyebrow">CENTRO DE MONITOREO</span><h1>Ocupación y flujo del aeropuerto</h1><p>{busy?'Recibiendo resultados del análisis':archived?'Revisa una grabación o inicia un nuevo monitoreo':'Configura las cámaras e inicia el monitoreo para ver resultados'}</p></div><button onClick={()=>onSetup()}>Configurar cámaras</button><button onClick={onReplay}>Videos y resultados</button></div>
    {error&&<div className="notice error">{error}</div>}
    <div className="monitor-filters aero-panel"><label>Nivel<select value={level} onChange={e=>{setLevel(e.target.value);setCamera('all');setZone('all');}}>{[1,2,3,4].map(n=><option key={n} value={`lap-${n}`}>LAP · Nivel {n}</option>)}</select></label><label>Cámara<select value={camera} onChange={e=>{setCamera(e.target.value);setZone('all');}}><option value="all">Todas las del nivel</option>{config.cameras.filter(c=>(c.planId||'custom')===level).map(c=><option key={c.id} value={c.id}>{c.name||c.id}</option>)}</select></label><label>Zona de imagen<select value={zone} onChange={e=>setZone(e.target.value)}><option value="all">Todas las zonas</option>{zoneNames.map(n=><option key={n}>{n}</option>)}</select></label><label>Rendimiento<select disabled={busy} value={quality} onChange={e=>setQuality(+e.target.value)}><option value="480">Priorizar respuesta</option><option value="640">Equilibrado</option><option value="960">Priorizar detalle</option></select></label><label className="check"><input disabled={busy} type="checkbox" checked={allLevels} onChange={e=>setAllLevels(e.target.checked)}/> Procesar todos los niveles</label><label className="check"><input disabled={busy} type="checkbox" checked={unified} onChange={e=>setUnified(e.target.checked)}/> Asociar recorridos calibrados</label><button className="primary" disabled={session.busy||(!busy&&!(camera==='all'&&allLevels?config.cameras:cameras).some(c=>c.active!==false))} onClick={()=>void session.action(async()=>{if(busy){await session.post('stop',{});return;}await session.save();await session.post('start',{detector:'yolo',combined:true,inferenceSize:quality,cameraIds:camera==='all'?(allLevels?config.cameras:cameras).filter(c=>c.active!==false).map(c=>c.id):[camera],requireUnified:unified});})}>{busy?'Detener monitoreo':'Iniciar monitoreo'}</button></div>
    {(busy||(!historyLoading&&!archived))&&<div className="overview-stats">{[['Cámaras seleccionadas',cameras.length],['Entradas registradas',entries],['Salidas registradas',exits],['Tiempo de análisis',formatTime(base.t)]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>}
    {plan&&!historyLoading&&(busy||!archived||(camera!=='all'&&!cameraAnalytics[camera]))&&<section className="aero-panel">{!busy&&archived&&camera==='all'&&<p className="subtle">Mapa del análisis {new Date(archived.created).toLocaleString('es-PE')}: {archived.cameras.map((c:any)=>c.name).join(', ')}. Las tarjetas conservan el último resultado de cada cámara.</p>}<MapCanvas key={level} config={plan} state={state} connected={session.connected} selectedCamera={camera==='all'?'':camera} onCamera={id=>setCamera(id)}/>{camera!=='all'&&<p className="subtle">El plano muestra esta cámara completa. El filtro de zona de imagen selecciona los indicadores y episodios de la tarjeta.</p>}</section>}
    {!busy&&historyLoading&&<div className="monitor-loading" role="status">Cargando el monitoreo guardado…</div>}{!busy&&!historyLoading&&archived&&<ReplayWorkspace active={active} embedded selectedLevel={level} cameraFilter={camera} zoneFilter={zone} currentConfig={config} onCamera={id=>{setCamera(id);setZone('all');}}/>}
    {busy&&<ExecutiveSummary rows={trend}/>}
    <details className="camera-history-summary" open={busy||zone!=='all'||undefined}><summary>Resumen de análisis completados</summary><p className="summary-context">Resultado final más reciente de cada cámara. Para revisar un instante, utiliza la reproducción de arriba.</p><div className="monitor-camera-grid">{cameras.map(c=>{const status=session.state.cameras.find(v=>v.id===c.id);const a=cameraAnalytics[c.id],zones=a?.occupancy?.zones?.filter((z:any)=>zone==='all'||z.name===zone)||[];return <article className="aero-panel" key={c.id}><div className="panel-heading"><h2>{c.name||c.id}</h2><button disabled={busy} onClick={()=>onSetup(c.id)}>Configurar</button></div>{busy&&<CameraVideo camera={c} state={session.state} connected={session.connected}/>}{!busy&&archived?.latestByCamera?.[c.id]&&<small>Análisis: {new Date(archived.latestByCamera[c.id].created).toLocaleString('es-PE')}</small>}<p>{c.active===false?'Cámara desactivada · ':''}{a?`Última muestra: ${formatTime(a.t)} del análisis`:'Todavía no hay resultados de esta cámara'}</p><div className="feed-metrics">{busy&&status?.duration&&<span>Video: {formatTime(status.sourceTime||0)} / {formatTime(status.duration)}</span>}<span>{a?.occupancy?.count??'—'} personas observadas</span><span>Máximo: {a?.occupancy?.peak??'—'}</span></div>{zones.map((z:any)=><p key={z.id}>{z.name}: {z.count} personas · máximo {z.peak}{z.alert?' · Concentración sostenida':''}</p>)}{a?.dense&&<p>Conteo especializado: {a.dense.count} · muestra {formatTime(a.dense.t)} (no se suma al conteo de detección)</p>}{a?.denseError&&<p className="notice error">Conteo especializado: {a.denseError}</p>}{a?.crossings?.map((l:any)=><p key={l.id}>{l.name}: {l.entries} entradas · {l.exits} salidas</p>)}{a?.occupancy?.episodes?.filter((e:any)=>zone==='all'||e.zone===zone).slice(-3).map((e:any)=><p key={e.id}>Concentración en {e.zone}: {formatTime(e.start)}–{e.end==null?'en curso':formatTime(e.end)} · máximo {e.peak}</p>)}</article>;})}</div></details>
  </div>;
}
