import {useRef,useState} from 'react';
import type {Config,SessionState,HeatCell} from './types';
import {formatTime} from './types';
import MapCanvas from './MapCanvas';

export default function ReportDetails({config,state,kind}:{config:Config;state:SessionState;kind:string}){
 const mapRef=useRef<HTMLDivElement>(null);
 const [focus,setFocus]=useState<HeatCell>();
 const pid=state.planId||config.planId;
 const plan={...config,...(pid===config.planId?{}:config.plans?.[pid||'custom']),planId:pid};
 if(kind==='occupancy')return <table><thead><tr><th>Zona configurada</th><th>Personas en la muestra</th><th>Pico</th></tr></thead><tbody>{state.analytics.zones.map(z=><tr key={z.name}><td>{z.name}</td><td>{z.count}</td><td>{z.peak??'—'}</td></tr>)}</tbody><caption>Estas zonas se dibujan en Configuración → Zonas del plano. {state.analytics.zones.length?'':'Todavía no hay zonas del plano con datos.'}</caption></table>;
 if(kind==='flow'){const bins=new Map<number,{sum:number;n:number;peak:number}>();for(const s of state.series||[]){const h=Math.floor(s.t/3600),b=bins.get(h)||{sum:0,n:0,peak:0};b.sum+=s.count;b.n++;b.peak=Math.max(b.peak,s.count);bins.set(h,b);}return <table><thead><tr><th>Hora desde el inicio</th><th>Promedio observado</th><th>Pico</th><th>Muestras</th></tr></thead><tbody>{[...bins].map(([h,b])=><tr key={h}><td>{h}:00–{h+1}:00</td><td>{(b.sum/b.n).toFixed(1)}</td><td>{b.peak}</td><td>{b.n}</td></tr>)}</tbody><caption>{bins.size?'Hora relativa del video; no fecha de grabación.':'No hay serie horaria disponible en esta sesión. Consulta el historial de videos.'}</caption></table>;}
 if(kind==='access-events')return <table><thead><tr><th>Cámara / local</th><th>Movimiento</th><th>Instante del video</th></tr></thead><tbody>{Object.entries(state.cameraAnalytics||{}).flatMap(([cid,a])=>(a.crossings||[]).flatMap((l:any)=>(l.events||[]).map((e:any,i:number)=><tr key={cid+l.id+i}><td>{config.cameras.find(c=>c.id===cid)?.name||cid} / {l.place?.name?`${l.place.name} / ${l.name}`:l.name}</td><td>{e.direction==='entries'?'Entrada':'Salida'}</td><td>{formatTime(e.t)}</td></tr>)))}</tbody><caption>Últimos 1000 eventos por acceso. Los análisis anteriores no guardaban el detalle de eventos; vuelve a procesar para obtenerlo.</caption></table>;
 if(kind==='trajectories')return <><p>Los recorridos se inspeccionan en Videos y resultados → Personas e IDs. Aquí aparecen únicamente los recorridos retenidos en la sesión actual.</p><table><thead><tr><th>ID</th><th>Cámara</th><th>Posiciones registradas</th></tr></thead><tbody>{state.people.map(p=><tr key={p.id+p.camera}><td>{p.id}</td><td>{config.cameras.find(c=>c.id===p.camera)?.name||p.camera}</td><td>{p.history.length}</td></tr>)}</tbody></table></>;
 const heat=state.analytics.heat;
 return <div className="report-spatial"><p>Los sectores son celdas automáticas de presencia, no locales configurados ni alertas de aglomeración. Pulsa «Ubicar» para ver exactamente su posición y tamaño.</p><div className="report-sector-table"><table><thead><tr><th>Sector</th><th>Referencia cercana</th><th>Presencia relativa</th><th>Pico simultáneo en celda</th><th>Plano</th></tr></thead><tbody>{heat.slice(0,30).map((c,i)=>{const near=plan.cameras.filter(v=>(v.planId||'custom')===(pid||'custom')).sort((a,b)=>Math.hypot(a.x-c.x,a.y-c.y)-Math.hypot(b.x-c.x,b.y-c.y))[0];return <tr key={`${c.x}-${c.y}`}><td>S{i+1}</td><td>{near?`Cerca de ${near.name||near.id}`:plan.floor}</td><td>{Math.round(c.seconds/Math.max(1,...heat.map(v=>v.seconds))*100)}%</td><td>{c.peak}</td><td><button onClick={()=>{setFocus(c);mapRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"});}}>Ubicar S{i+1}</button></td></tr>;})}</tbody></table></div>{!heat.length?<p>No hay posiciones calibradas en este análisis.</p>:<div ref={mapRef}><MapCanvas config={plan} state={{...state,planId:pid}} connected selectedCamera="" onCamera={()=>{}} focusArea={focus}/>{focus&&<p>Sector seleccionado · {focus.size.toFixed(1)} × {focus.size.toFixed(1)} {plan.unit==='meters'?'m aproximados':'unidades'} · ({focus.x.toFixed(2)}, {focus.y.toFixed(2)})</p>}</div>}</div>;
}
