import type { Session } from './useSession';
import type { Config, SourceMode, View } from './types';
import { freshCamera, isActive, isStream } from './types';
import Icon from './Icon';
import { CameraEditor } from './CameraPanel';
import PlanWorkspace from './PlanWorkspace';

export function readiness(config: Config, session: Session) {
  const cameras=config.cameras;
  const mode=config.sourceMode||'recordings';
  const tests=cameras.filter(c=>session.state.sourceChecks?.[c.id]?.valid&&session.state.sourceChecks[c.id].source===c.source);
  const calibrated=cameras.filter(c=>c.pairs.length>=4).length;
  return [
    { title:'Proyecto', subtitle:'Espacio y modo de trabajo', done:!!config.airport?.trim()&&!!config.floor?.trim(), icon:'grid' },
    { title:'Cámaras', subtitle:`${cameras.length} cámaras · ${tests.length} probadas`, done:cameras.length>0&&cameras.every(c=>mode==='demo'||(c.source!==''&&isStream(c.source)===(mode==='live'))), icon:'camera' },
    { title:'Espacio y calibración', subtitle:!config.mapConfigured?'Falta el plano':mode==='demo'?'Espacio definido · sin calibración':`Espacio definido · ${calibrated}/${cameras.length} calibradas`, done:!!config.mapConfigured&&(mode==='demo'||(cameras.length>0&&cameras.every(c=>c.pairs.length>=4))), icon:'map' },
    { title:'Validación', subtitle:mode==='demo'?'Preparar demostración':'Validar antes de operar', done:mode==='demo'||(cameras.length>0&&tests.length===cameras.length&&(cameras.length===1||config.clocksVerified)), icon:'check' },
  ];
}

export default function SetupFlow({ session, selected, onSelected, onNavigate, step, setStep, startTest }: { session:Session;selected:string;onSelected:(s:string)=>void;onNavigate:(v:View)=>void;step:number;setStep:(v:number)=>void;startTest:()=>void }) {
  const config=session.config!;
  const camera=config.cameras.find(c=>c.id===selected);
  const disabled=isActive(session.state.status);
  const stages=readiness(config,session);
  const update=(patch:Partial<Config>)=>session.setConfig({...config,...patch});
  function addCamera() { const next=freshCamera(); next.x=config.width/2;next.y=config.height/2;if(config.sourceMode==='live')next.source=0;update({cameras:[...config.cameras,next],setupComplete:false});onSelected(next.id); }
  return <section className="setup-flow"><div className="page-heading"><div><span className="eyebrow">PUESTA EN MARCHA</span><h1>Prepara tu espacio de monitoreo</h1><p>La guía se actualiza con tu configuración. Puedes volver a cualquier paso.</p></div><span className="pill blue">{stages.filter(s=>s.done).length} de {stages.length} pasos preparados</span></div>
    <nav className="setup-steps">{stages.map((s,i)=><button key={s.title} className={`${step===i?'current':''} ${s.done?'done':''}`} onClick={()=>setStep(i)}><span className="step-number">{s.done?<Icon name="check" size={16}/>:i+1}</span><span><strong>{s.title}</strong><small>{s.subtitle}</small></span></button>)}</nav>
    {disabled&&<div className="notice warning"><Icon name="alert"/>Hay una sesión activa. Puedes revisar la guía; finaliza la sesión para editar fuentes o geometría.</div>}
    <div className="setup-body">
      {step===0&&<div className="project-step"><div className="step-intro"><span className="number-tile">01</span><h2>Un espacio, todas tus cámaras</h2><p>Define dónde trabajarás y qué tipo de fuentes usarás. Puedes cambiar de grabaciones a cámaras reales cuando completes la prueba.</p><div className="privacy-block"><Icon name="shield"/><div><strong>Tracking anónimo</strong><p>IDs temporales y trayectorias de sesión. Sin reconocimiento facial ni identidad personal.</p></div></div></div><div className="project-form"><div className="form-grid"><label>Aeropuerto o proyecto<input disabled={disabled} value={config.airport||''} placeholder="Nombre del aeropuerto" onChange={e=>update({airport:e.target.value})}/></label><label>Terminal y nivel<input disabled={disabled} value={config.floor||''} placeholder="Terminal A · Nivel 1" onChange={e=>update({floor:e.target.value})}/></label></div><h3>¿Cómo comenzarás?</h3><div className="mode-cards">{([{value:'recordings',title:'Videos grabados',icon:'report',text:'Valida detección y recorridos con tus grabaciones sincronizadas.'},{value:'live',title:'Cámaras en vivo',icon:'camera',text:'Conecta una o varias cámaras USB, RTSP o IP.'},{value:'demo',title:'Demostración',icon:'lab',text:'Explora las pantallas con nodos sintéticos; sin video de personas.'}] as {value:SourceMode;title:string;icon:string;text:string}[]).map(m=><button key={m.value} disabled={disabled} className={(config.sourceMode||'recordings')===m.value?'selected':''} onClick={()=>update({sourceMode:m.value,setupComplete:false})}><Icon name={m.icon} size={25}/><strong>{m.title}</strong><span>{m.text}</span><i>{(config.sourceMode||'recordings')===m.value?'Seleccionado':'Elegir'}</i></button>)}</div><p className="subtle">Las grabaciones sirven para simulación y validación. No se entrena un modelo automáticamente al cargarlas.</p></div></div>}
      {step===1&&<div className="source-step"><aside className="source-list"><div className="section-label"><h3>Fuentes del proyecto</h3><span>{config.cameras.length}</span></div>{config.cameras.map(c=><button key={c.id} className={selected===c.id?'selected':''} onClick={()=>onSelected(c.id)}><Icon name="camera"/><span><strong>{c.name||c.id}</strong><small>{c.id} · {c.source===''?'Sin fuente':isStream(c.source)?'En vivo':'Grabación'}</small></span><i className={`dot ${session.state.sourceChecks?.[c.id]?.source===c.source?'green':'amber'}`}/></button>)}<button disabled={disabled||config.cameras.length>=32} onClick={addCamera}><Icon name="plus"/> Añadir cámara</button><p className="subtle">Configura tantas cámaras como necesites dentro de la capacidad del equipo. Cada una tiene su fuente y calibración.</p></aside><div className="source-editor">{camera?<><div className="section-label"><h2>{camera.name||camera.id}</h2><button disabled={disabled} className="danger ghost" onClick={()=>{const rest=config.cameras.filter(c=>c.id!==selected).map(c=>({...c,links:c.links.filter(id=>id!==selected)}));update({cameras:rest});onSelected(rest[0]?.id||'');}}><Icon name="trash" size={15}/> Quitar</button></div><CameraEditor config={config} camera={camera} onChange={session.setConfig} session={session}/><div className="inline end"><button disabled={session.busy||disabled||camera.source===''} className="primary" onClick={startTest}><Icon name="lab"/> Probar esta fuente</button></div></>:<div className="empty-state"><Icon name="camera" size={36}/><h3>Comienza con tu primera cámara</h3><p>Agrega una fuente de video o una conexión en vivo.</p><button className="primary" onClick={addCamera}>Añadir cámara</button></div>}</div></div>}
      {step===2&&<PlanWorkspace session={session} selected={selected} onSelected={onSelected} startTest={startTest}/>}
      {step===3&&<div className="review-step"><div><h2>Comprueba el proyecto antes de iniciar</h2><p className="subtle">Las verificaciones cambian con tus cámaras, fuentes y calibraciones. Una casilla completada no sustituye la validación de precisión.</p><div className="readiness-list">{stages.slice(0,3).map(s=><div key={s.title}><span className={`check-circle ${s.done?'good':''}`}><Icon name={s.done?'check':'clock'} size={16}/></span><span><strong>{s.title}</strong><small>{s.subtitle}</small></span><b>{s.done?'Preparado':'Pendiente'}</b></div>)}</div><label className="check"><input type="checkbox" disabled={disabled} checked={config.clocksVerified} onChange={e=>update({clocksVerified:e.target.checked})}/> Verifiqué el mismo tiempo de contenido en las cámaras y ajusté sus desfases.</label><p className="subtle">Si no está verificado, el sistema mantiene IDs locales y no asocia personas entre cámaras. La llegada de dos streams al mismo equipo no demuestra sincronización.</p></div><div className="review-summary"><Icon name="shield" size={30}/><h3>{config.airport}</h3><p>{config.floor}</p><dl><div><dt>Cámaras</dt><dd>{config.cameras.length}</dd></div><div><dt>Zonas dibujadas</dt><dd>{config.zones.length}</dd></div><div><dt>Fuentes probadas</dt><dd>{config.cameras.filter(c=>session.state.sourceChecks?.[c.id]?.source===c.source).length}</dd></div><div><dt>Escala</dt><dd>{config.unit==='meters'?'Metros':'Relativa'}</dd></div></dl><button className="primary" disabled={disabled||session.busy||!stages.every(s=>s.done)} onClick={()=>void session.action(async()=>{await session.save({...config,setupComplete:true});onNavigate('overview');})}>Guardar y abrir centro <Icon name="arrow" size={16}/></button><button onClick={()=>onNavigate('lab')}>Continuar las pruebas en laboratorio</button></div></div>}
    </div><footer className="setup-footer"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Anterior</button><span><Icon name="shield" size={14}/> Sin identificación personal</span><div className="inline"><button disabled={disabled||session.busy} onClick={()=>void session.action(async()=>{await session.save();session.setNotice('Borrador guardado. Puedes continuar después.');})}>Guardar progreso</button>{step<3&&<button className="primary" disabled={!stages[step].done} onClick={()=>setStep(step+1)}>Siguiente <Icon name="arrow" size={15}/></button>}</div></footer>
  </section>;
}
