import { useRef, useState } from 'react';
import type { Session } from './useSession';
import type { Camera, Config, Point, SourceMode, View } from './types';
import { freshCamera, isActive, isStream } from './types';
import Icon from './Icon';
import MapCanvas from './MapCanvas';
import type { MapTool } from './MapCanvas';
import { CameraEditor, CameraVideo } from './CameraPanel';
import PlanCropper from './PlanCropper';

export function readiness(config: Config, session: Session) {
  const cameras=config.cameras;
  const mode=config.sourceMode||'recordings';
  const tests=cameras.filter(c=>session.state.sourceChecks?.[c.id]?.valid&&session.state.sourceChecks[c.id].source===c.source);
  return [
    { title:'Proyecto', subtitle:'Espacio y modo de trabajo', done:!!config.airport?.trim()&&!!config.floor?.trim(), icon:'grid' },
    { title:'Fuentes', subtitle:`${cameras.length} cámaras · ${tests.length} probadas`, done:cameras.length>0&&cameras.every(c=>mode==='demo'||(c.source!==''&&isStream(c.source)===(mode==='live'))), icon:'camera' },
    { title:'Plano', subtitle:config.mapConfigured?'Espacio definido':'Importar o dibujar', done:!!config.mapConfigured, icon:'map' },
    { title:'Calibración', subtitle:mode==='demo'?'No aplica a simulación':`${cameras.filter(c=>c.pairs.length>=4).length} / ${cameras.length} con referencias`, done:mode==='demo'||(cameras.length>0&&cameras.every(c=>c.pairs.length>=4)), icon:'pin' },
    { title:'Comprobación', subtitle:mode==='demo'?'Preparar demostración':'Validar antes de operar', done:mode==='demo'||(cameras.length>0&&tests.length===cameras.length&&(cameras.length===1||config.clocksVerified)), icon:'check' },
  ];
}

export default function SetupFlow({ session, selected, onSelected, onNavigate, step, setStep, startTest }: { session:Session;selected:string;onSelected:(s:string)=>void;onNavigate:(v:View)=>void;step:number;setStep:(v:number)=>void;startTest:()=>void }) {
  const config=session.config!;
  const camera=config.cameras.find(c=>c.id===selected);
  const disabled=isActive(session.state.status);
  const stages=readiness(config,session);
  const [tool,setTool]=useState<MapTool>('select');
  const [pending,setPending]=useState<Point|null>(null);
  const [page,setPage]=useState(1);
  const [reference,setReference]=useState(1);
  const [meters,setMeters]=useState(1);
  const [cropSource,setCropSource]=useState<{src:string;name:string;targetWidth:number}|null>(null);
  const [zoneMode,setZoneMode]=useState(false);
  const [zoneDraft,setZoneDraft]=useState<Point[]>([]);
  const file=useRef<HTMLInputElement>(null);
  const update=(patch:Partial<Config>)=>session.setConfig({...config,...patch});
  function applyPlan(background:string,width:number,height:number,zones:Config['zones'],warnings:string[]|undefined,name:string) {
    update({background,width,height,zones,cameras:config.cameras.map(c=>({...c,x:Math.min(c.x,width),y:Math.min(c.y,height),pairs:[]})),mapConfigured:true,unit:'relative',planName:name,importWarnings:warnings});
    session.setNotice('Plano importado. Revisa sus zonas y vuelve a calibrar las cámaras para este plano.');
  }
  function addCamera() { const next=freshCamera(); next.x=config.width/2;next.y=config.height/2;if(config.sourceMode==='live')next.source=0;update({cameras:[...config.cameras,next],setupComplete:false});onSelected(next.id); }
  function patchCamera(patch:Partial<Camera>) { update({cameras:config.cameras.map(c=>c.id===selected?{...c,...patch}:c)}); }
  function convertScale() {
    if(!Number.isFinite(reference)||!Number.isFinite(meters)||reference<=0||meters<=0){session.setError('Las distancias de referencia deben ser positivas.');return;}
    const ratio=meters/reference;
    const point=(p:Point):Point=>[p[0]*ratio,p[1]*ratio];
    update({unit:'meters',width:config.width*ratio,height:config.height*ratio,radius:config.radius*ratio,matchDistance:config.matchDistance*ratio,cameras:config.cameras.map(c=>({...c,x:c.x*ratio,y:c.y*ratio,range:(c.range??3)*ratio,height:(c.height??3)*ratio,pairs:c.pairs.map(p=>[p[0],p[1],p[2]*ratio,p[3]*ratio])})),zones:config.zones.map(z=>({...z,points:z.points.map(point)}))});
    session.setNotice('Geometría y distancias convertidas con la referencia indicada. Guarda para conservar la escala.');
  }
  return <section className="setup-flow"><div className="page-heading"><div><span className="eyebrow">PUESTA EN MARCHA</span><h1>Prepara tu espacio de monitoreo</h1><p>La guía se actualiza con tu configuración. Puedes volver a cualquier paso.</p></div><span className="pill blue">{stages.filter(s=>s.done).length} de 5 pasos preparados</span></div>
    <nav className="setup-steps">{stages.map((s,i)=><button key={s.title} className={`${step===i?'current':''} ${s.done?'done':''}`} onClick={()=>{setStep(i);setPending(null);setTool('select');}}><span className="step-number">{s.done?<Icon name="check" size={16}/>:i+1}</span><span><strong>{s.title}</strong><small>{s.subtitle}</small></span></button>)}</nav>
    {disabled&&<div className="notice warning"><Icon name="alert"/>Hay una sesión activa. Puedes revisar la guía; finaliza la sesión para editar fuentes o geometría.</div>}
    <div className="setup-body">
      {step===0&&<div className="project-step"><div className="step-intro"><span className="number-tile">01</span><h2>Un espacio, todas tus cámaras</h2><p>Define dónde trabajarás y qué tipo de fuentes usarás. Puedes cambiar de grabaciones a cámaras reales cuando completes la prueba.</p><div className="privacy-block"><Icon name="shield"/><div><strong>Tracking anónimo</strong><p>IDs temporales y trayectorias de sesión. Sin reconocimiento facial ni identidad personal.</p></div></div></div><div className="project-form"><div className="form-grid"><label>Aeropuerto o proyecto<input disabled={disabled} value={config.airport||''} placeholder="Nombre del aeropuerto" onChange={e=>update({airport:e.target.value})}/></label><label>Terminal y nivel<input disabled={disabled} value={config.floor||''} placeholder="Terminal A · Nivel 1" onChange={e=>update({floor:e.target.value})}/></label></div><h3>¿Cómo comenzarás?</h3><div className="mode-cards">{([{value:'recordings',title:'Videos grabados',icon:'report',text:'Valida detección y recorridos con tus grabaciones sincronizadas.'},{value:'live',title:'Cámaras en vivo',icon:'camera',text:'Conecta una o varias cámaras USB, RTSP o IP.'},{value:'demo',title:'Demostración',icon:'lab',text:'Explora las pantallas con nodos sintéticos; sin video de personas.'}] as {value:SourceMode;title:string;icon:string;text:string}[]).map(m=><button key={m.value} disabled={disabled} className={(config.sourceMode||'recordings')===m.value?'selected':''} onClick={()=>update({sourceMode:m.value,setupComplete:false})}><Icon name={m.icon} size={25}/><strong>{m.title}</strong><span>{m.text}</span><i>{(config.sourceMode||'recordings')===m.value?'Seleccionado':'Elegir'}</i></button>)}</div><p className="subtle">Las grabaciones sirven para simulación y validación. No se entrena un modelo automáticamente al cargarlas.</p></div></div>}
      {step===1&&<div className="source-step"><aside className="source-list"><div className="section-label"><h3>Fuentes del proyecto</h3><span>{config.cameras.length}</span></div>{config.cameras.map(c=><button key={c.id} className={selected===c.id?'selected':''} onClick={()=>onSelected(c.id)}><Icon name="camera"/><span><strong>{c.name||c.id}</strong><small>{c.id} · {c.source===''?'Sin fuente':isStream(c.source)?'En vivo':'Grabación'}</small></span><i className={`dot ${session.state.sourceChecks?.[c.id]?.source===c.source?'green':'amber'}`}/></button>)}<button disabled={disabled||config.cameras.length>=32} onClick={addCamera}><Icon name="plus"/> Añadir cámara</button><p className="subtle">Configura tantas cámaras como necesites dentro de la capacidad del equipo. Cada una tiene su fuente y calibración.</p></aside><div className="source-editor">{camera?<><div className="section-label"><h2>{camera.name||camera.id}</h2><button disabled={disabled} className="danger ghost" onClick={()=>{const rest=config.cameras.filter(c=>c.id!==selected).map(c=>({...c,links:c.links.filter(id=>id!==selected)}));update({cameras:rest});onSelected(rest[0]?.id||'');}}><Icon name="trash" size={15}/> Quitar</button></div><CameraEditor config={config} camera={camera} onChange={session.setConfig} session={session}/><div className="inline end"><button disabled={session.busy||disabled||camera.source===''} className="primary" onClick={startTest}><Icon name="lab"/> Probar esta fuente</button></div></>:<div className="empty-state"><Icon name="camera" size={36}/><h3>Comienza con tu primera cámara</h3><p>Agrega una fuente de video o una conexión en vivo.</p><button className="primary" onClick={addCamera}>Añadir cámara</button></div>}</div></div>}
      {step===2&&<div className="plan-step"><aside className="plan-options"><h3>Plano del espacio</h3><button disabled={disabled||session.busy} className="primary" onClick={()=>file.current?.click()}><Icon name="upload"/> Importar plano</button><label>Página del PDF<input type="number" min="1" max="1001" value={page} onChange={e=>setPage(+e.target.value)}/></label><small className="subtle">PNG, JPG, PDF, DXF. DWG requiere conversor LibreDWG. Puedes clasificar las formas después de importarlas.</small><input ref={file} type="file" hidden accept=".png,.jpg,.jpeg,.webp,.pdf,.dxf,.dwg" onChange={e=>{const selectedFile=e.target.files?.[0];e.target.value='';if(!selectedFile)return;const raster=/\.(png|jpe?g|webp|pdf)$/i.test(selectedFile.name);void session.action(async()=>{const result=await session.post(`import-plan?name=${encodeURIComponent(selectedFile.name)}&width=${config.width}&page=${page-1}`,selectedFile,true);if(raster)setCropSource({src:result.background,name:selectedFile.name,targetWidth:config.width});else applyPlan(result.background,result.width,result.height,result.zones,result.warnings,selectedFile.name);});}}/>
        {cropSource&&<PlanCropper src={cropSource.src} session={session} targetWidth={cropSource.targetWidth} onCancel={()=>setCropSource(null)} onConfirm={(background,w,h,warnings)=>{applyPlan(background,w,h,[],warnings,cropSource.name);setCropSource(null);}}/>}
        <hr/><label>Ancho del plano<input type="number" min="1" max="10000" disabled={disabled} value={config.width} onChange={e=>update({width:+e.target.value,setupComplete:false})}/></label><label>Alto del plano<input type="number" min="1" max="10000" disabled={disabled} value={config.height} onChange={e=>update({height:+e.target.value,setupComplete:false})}/></label><button disabled={disabled} onClick={()=>update({background:'',planName:'Plano en blanco',mapConfigured:true})}>Crear plano en blanco</button><p className="subtle">Usa las herramientas del mapa para dibujar y mover muros, áreas, polígonos o círculos.</p><hr/><h3>Convertir a metros</h3><label>Distancia conocida en unidades<input type="number" min="0.001" step="0.1" value={reference} onChange={e=>setReference(+e.target.value)}/></label><label>Distancia real (metros)<input type="number" min="0.001" step="0.1" value={meters} onChange={e=>setMeters(+e.target.value)}/></label><button disabled={disabled||config.unit==='meters'} onClick={convertScale}>{config.unit==='meters'?'Escala métrica aplicada':'Aplicar referencia medida'}</button></aside><div className="plan-editor"><MapCanvas config={config} state={session.state} connected={session.connected} editable={!disabled} selectedCamera={selected} onCamera={onSelected} onChange={session.setConfig} tool={tool} onTool={setTool}/>{config.importWarnings?.map((w,i)=><p key={i} className="notice compact">{w}</p>)}<div className="inline spread"><span className="subtle">{config.planName||'Espacio de coordenadas relativas'}</span><label className="check"><input type="checkbox" disabled={disabled} checked={!!config.mapConfigured} onChange={e=>update({mapConfigured:e.target.checked})}/> Este plano representa el espacio que voy a monitorear</label></div></div></div>}
      {step===3&&<div className="calibration-step"><div className="calibration-header"><div><h2>Une la imagen de cada cámara con el plano</h2><p>Marca un punto fijo del suelo en el video y luego su misma ubicación en el plano. Repite con 4 puntos como mínimo.</p></div><select aria-label="Cámara a calibrar" value={selected} onChange={e=>{onSelected(e.target.value);setPending(null);}}>{config.cameras.map(c=><option value={c.id} key={c.id}>{c.id} · {c.pairs.length} referencias</option>)}</select></div>{config.sourceMode==='demo'&&<div className="notice">La demostración usa posiciones sintéticas. La calibración será necesaria cuando conectes fuentes reales.</div>}<div className="calibration-panes"><div><CameraVideo camera={camera} state={session.state} connected={session.connected} mode={zoneMode?'zone':(!disabled?'calibration':undefined)} pending={pending} zonePoints={zoneMode?zoneDraft:undefined} onPoint={p=>{if(zoneMode){setZoneDraft(v=>[...v,p]);return;}setPending(p);setTool('calibrate');session.setNotice('Ahora marca ese mismo punto del suelo en el plano.');}}/><p className="subtle">Primero prueba y finaliza la cámara para obtener una imagen retenida. No uses la cabeza de una persona como referencia del suelo.</p><button disabled={disabled||!camera||camera.source===''} onClick={startTest}><Icon name="lab"/> Obtener imagen de prueba</button>
        <div className="zone-tool"><h3>Zona útil de detección (opcional)</h3><p className="subtle">Delimita en el video el área donde sí deben contarse personas — excluye espejos, reflejos o zonas fuera del alcance real de esta cámara. Sin zona marcada, se detecta en todo el cuadro.</p>{!zoneMode?<div className="inline"><button onClick={()=>{setZoneMode(true);setZoneDraft(camera?.detectionZone?camera.detectionZone.slice():[]);}}>{camera?.detectionZone?.length?'Editar zona':'Marcar zona'}</button>{!!camera?.detectionZone?.length&&<button className="danger ghost" onClick={()=>patchCamera({detectionZone:undefined})}>Quitar zona</button>}</div>:<div className="inline"><span className="pill blue">{zoneDraft.length} puntos · mínimo 3</span><button disabled={!zoneDraft.length} onClick={()=>setZoneDraft(v=>v.slice(0,-1))}>Deshacer punto</button><button disabled={zoneDraft.length<3} onClick={()=>{patchCamera({detectionZone:zoneDraft});setZoneMode(false);session.setNotice('Zona de detección lista. Guarda la configuración para conservarla.');}}>Cerrar y guardar zona</button><button onClick={()=>setZoneMode(false)}>Cancelar</button></div>}</div></div><MapCanvas config={config} state={session.state} connected={session.connected} selectedCamera={selected} onCamera={onSelected} onChange={session.setConfig} editable={!disabled} tool="calibrate" onCalibrationPoint={p=>{if(!pending||!camera)return;patchCamera({pairs:[...camera.pairs,[...pending,...p]]});setPending(null);}}/></div><div className="calibration-actions"><span className="pill blue">{camera?.pairs.length||0} puntos · recomendado 6–8</span><button disabled={disabled||!camera?.pairs.length} onClick={()=>patchCamera({pairs:camera!.pairs.slice(0,-1)})}>Deshacer último</button><button disabled={disabled||!camera?.pairs.length} onClick={()=>patchCamera({pairs:[]})}>Reiniciar calibración</button><button disabled={disabled||session.busy} className="primary" onClick={()=>void session.action(async()=>{await session.save();session.setNotice('Calibración guardada y geometría comprobada.');})}>Guardar referencias</button></div><p className="subtle">P2PNet detecta cabezas; se valida en video. Para proyectar al suelo se necesita un detector de cuerpos o un método de localización de pies validado.</p></div>}
      {step===4&&<div className="review-step"><div><h2>Comprueba el proyecto antes de iniciar</h2><p className="subtle">Las verificaciones cambian con tus cámaras, fuentes y calibraciones. Una casilla completada no sustituye la validación de precisión.</p><div className="readiness-list">{stages.slice(0,4).map(s=><div key={s.title}><span className={`check-circle ${s.done?'good':''}`}><Icon name={s.done?'check':'clock'} size={16}/></span><span><strong>{s.title}</strong><small>{s.subtitle}</small></span><b>{s.done?'Preparado':'Pendiente'}</b></div>)}</div><label className="check"><input type="checkbox" disabled={disabled} checked={config.clocksVerified} onChange={e=>update({clocksVerified:e.target.checked})}/> Verifiqué el mismo tiempo de contenido en las cámaras y ajusté sus desfases.</label><p className="subtle">Si no está verificado, el sistema mantiene IDs locales y no asocia personas entre cámaras. La llegada de dos streams al mismo equipo no demuestra sincronización.</p></div><div className="review-summary"><Icon name="shield" size={30}/><h3>{config.airport}</h3><p>{config.floor}</p><dl><div><dt>Cámaras</dt><dd>{config.cameras.length}</dd></div><div><dt>Zonas dibujadas</dt><dd>{config.zones.length}</dd></div><div><dt>Fuentes probadas</dt><dd>{config.cameras.filter(c=>session.state.sourceChecks?.[c.id]?.source===c.source).length}</dd></div><div><dt>Escala</dt><dd>{config.unit==='meters'?'Metros':'Relativa'}</dd></div></dl><button className="primary" disabled={disabled||session.busy||!stages.every(s=>s.done)} onClick={()=>void session.action(async()=>{await session.save({...config,setupComplete:true});onNavigate('overview');})}>Guardar y abrir centro <Icon name="arrow" size={16}/></button><button onClick={()=>onNavigate('lab')}>Continuar las pruebas en laboratorio</button></div></div>}
    </div><footer className="setup-footer"><button disabled={step===0} onClick={()=>setStep(step-1)}>← Anterior</button><span><Icon name="shield" size={14}/> Sin identificación personal</span><div className="inline"><button disabled={disabled||session.busy} onClick={()=>void session.action(async()=>{await session.save();session.setNotice('Borrador guardado. Puedes continuar después.');})}>Guardar progreso</button>{step<4&&<button className="primary" disabled={!stages[step].done} onClick={()=>setStep(step+1)}>Siguiente <Icon name="arrow" size={15}/></button>}</div></footer>
  </section>;
}
