"""PostgreSQL operativo, activado explícitamente después de migrar y verificar.

Sin fallback: una caída de PostgreSQL nunca abre un segundo conjunto de datos.
Cada instalación y proyecto tiene un espacio independiente. Los archivos previos
se conservan como respaldo, pero no se consultan cuando este backend está activo.
"""
import hashlib
import json
import os
import re
import sqlite3
import threading
from contextlib import closing
from pathlib import Path

_root = None
_installation = None
_prepared = set()
_prepare_lock = threading.Lock()


def is_database_error(exc):
    if isinstance(exc, sqlite3.OperationalError):
        return True
    try:
        import psycopg
        return isinstance(exc, psycopg.Error)
    except ImportError:
        return False


def configure(root):
    global _root, _installation
    root = Path(root).resolve()
    marker = root / 'config/storage.local.json'
    _root, _installation = None, None
    _prepared.clear()
    if marker.exists():
        data = json.loads(marker.read_text(encoding='utf-8'))
        if data.get('backend') != 'postgresql' or not data.get('installation'):
            raise ValueError('Configuración de almacenamiento inválida.')
        if not os.environ.get('AEROTRACK_DATABASE_URL'):
            raise RuntimeError('PostgreSQL está activado pero falta AEROTRACK_DATABASE_URL.')
        _root, _installation = root, data['installation']


def enabled(path):
    return _root is not None and Path(path).resolve().is_relative_to(_root / 'config')


def connect_db():
    import psycopg
    return psycopg.connect(os.environ['AEROTRACK_DATABASE_URL'], connect_timeout=5,
                           options='-c statement_timeout=30000')


def setup_documents(db):
    db.execute('''CREATE TABLE IF NOT EXISTS public.aero_documents (
        installation text NOT NULL, key text NOT NULL, content jsonb NOT NULL,
        updated_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(installation,key))''')


def key_for(path):
    return Path(path).resolve().relative_to(_root).as_posix()


def read_document(path):
    with connect_db() as db:
        row = db.execute('SELECT content FROM public.aero_documents WHERE installation=%s AND key=%s',
                         (_installation, key_for(path))).fetchone()
    if row is None:
        raise FileNotFoundError(str(path))
    return row[0]


def write_document(path, data):
    from psycopg.types.json import Jsonb
    with connect_db() as db:
        db.execute('''INSERT INTO public.aero_documents(installation,key,content) VALUES(%s,%s,%s)
            ON CONFLICT(installation,key) DO UPDATE SET content=excluded.content,updated_at=now()''',
                   (_installation, key_for(path), Jsonb(data)))


def delete_document(path):
    with connect_db() as db:
        db.execute('DELETE FROM public.aero_documents WHERE installation=%s AND key=%s',
                   (_installation, key_for(path)))


def schema_for(installation, project):
    return 'aero_p_' + hashlib.sha256((installation + ':' + project).encode()).hexdigest()[:24]


# Correspondencias explícitas para las únicas operaciones REPLACE del dominio.
# Se usa UPSERT, nunca DELETE+INSERT (que perdería relaciones dependientes).
REPLACEMENTS = {
    'appearance_meta': ('clave valor', 'clave'),
    'appearance_people': ('id suma muestras camaras apariciones primera_vez ultima_vez', 'id'),
    'appearance_views': ('persona tramo camara prototipo muestras', 'persona tramo'),
    'commercial_imports': ('id nombre dataset filas creado', 'id'),
    'commercial_sales': ('negocio_id fecha hora monto transacciones dataset import_id', 'negocio_id fecha hora dataset'),
    'commercial_traffic': ('session negocio_id fecha hora entradas salidas coverage dataset', 'session negocio_id fecha hora dataset'),
    'commercial_incidents': ('id negocio_id inicio duracion pico dataset', 'id'),
    'insights_hourly': ('session negocio_id fecha hora exposicion visitas permanencia_s cobertura_s dataset', 'session negocio_id fecha hora dataset'),
}


def translate(query):
    # Solo SQL estático del proyecto; los valores siempre son parámetros separados.
    query = query.strip().rstrip(';')
    if query == "SELECT 1 FROM sqlite_master WHERE type='table' AND name='ventas'":
        return "SELECT 1 FROM information_schema.tables WHERE table_schema=current_schema() AND table_name='ventas'"
    query = query.replace('INTEGER PRIMARY KEY AUTOINCREMENT', 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    query = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', query)
    query = re.sub(r'\bBLOB\b', 'BYTEA', query)
    query = query.replace('dataset="demo"', "dataset='demo'")
    query = query.replace('conteo_total = conteo_total +', 'conteo_total = trafico_historico.conteo_total +')
    query = query.replace('muestras = muestras +', 'muestras = trafico_historico.muestras +')
    query = query.replace('MAX(pico, excluded.pico)', 'GREATEST(trafico_historico.pico, excluded.pico)')
    if query.upper().startswith('INSERT OR IGNORE INTO '):
        query = re.sub('INSERT OR IGNORE INTO', 'INSERT INTO', query, count=1, flags=re.I) + ' ON CONFLICT DO NOTHING'
    match = re.match(r'INSERT OR REPLACE INTO (\w+)\s+VALUES', query, flags=re.I)
    if match:
        table = match[1]
        if table not in REPLACEMENTS:
            raise ValueError('Operación PostgreSQL no definida: ' + table)
        cols, keys = (value.split() for value in REPLACEMENTS[table])
        query = re.sub('INSERT OR REPLACE INTO', 'INSERT INTO', query, count=1, flags=re.I)
        query += ' ON CONFLICT (' + ','.join(keys) + ') DO UPDATE SET ' + ','.join(c + '=excluded.' + c for c in cols if c not in keys)
    # No sustituir signos de interrogación dentro de literales SQL.
    parts = re.split("('(?:''|[^'])*')", query)
    return ''.join(part.replace('?', '%s') if i % 2 == 0 else part for i, part in enumerate(parts))


class BusinessConnection:
    """Interfaz DB-API mínima compatible con los repositorios existentes."""
    def __init__(self, db):
        self.db = db

    def execute(self, query, params=()):
        import psycopg
        try:
            return self.db.execute(translate(query), params or None)
        except psycopg.IntegrityError as exc:
            raise sqlite3.IntegrityError('Conflicto de integridad en PostgreSQL.') from exc
        except psycopg.Error as exc:
            raise sqlite3.OperationalError('PostgreSQL no pudo completar la operación (' + type(exc).__name__ + ').') from exc

    def executemany(self, query, rows):
        import psycopg
        try:
            with self.db.cursor() as cursor:
                cursor.executemany(translate(query), rows)
        except psycopg.IntegrityError as exc:
            raise sqlite3.IntegrityError('Conflicto de integridad en PostgreSQL.') from exc
        except psycopg.Error as exc:
            raise sqlite3.OperationalError('PostgreSQL no pudo guardar el lote (' + type(exc).__name__ + ').') from exc

    def executescript(self, script):
        for statement in script.split(';'):
            if statement.strip():
                self.execute(statement)

    def commit(self):
        self.db.commit()

    def rollback(self):
        self.db.rollback()

    def close(self):
        self.db.close()

    def __enter__(self):
        return self

    def __exit__(self, typ, value, traceback):
        self.rollback() if typ else self.commit()


def prepare_business(db, installation, project):
    from psycopg import sql
    from business_data import ESQUEMA, NEGOCIOS_ESQUEMA
    from commercial import SCHEMA as commerce
    from insights.ventas import SCHEMA as insights
    schema = schema_for(installation, project)
    db.execute(sql.SQL('CREATE SCHEMA IF NOT EXISTS {}').format(sql.Identifier(schema)))
    db.execute(sql.SQL('SET search_path TO {}, public').format(sql.Identifier(schema)))
    con = BusinessConnection(db)
    con.executescript(ESQUEMA + NEGOCIOS_ESQUEMA + commerce + insights)
    con.execute('INSERT OR IGNORE INTO negocio_puertas SELECT id,camara_id,linea_id FROM negocios WHERE camara_id IS NOT NULL AND linea_id IS NOT NULL')
    # Vista espacial: mismos datos, sin duplicar ubicaciones ni inventar latitud.
    db.execute('''CREATE OR REPLACE VIEW negocio_geometrias AS SELECT negocio_id,plano_id,
        ST_SetSRID(ST_MakePoint(x,y),0) AS position FROM negocio_ubicaciones''')
    return con


def business_connect(path):
    db = connect_db()
    try:
        from psycopg import sql
        project = Path(path).stem
        schema = schema_for(_installation, project)
        with _prepare_lock:
            if schema not in _prepared:
                prepare_business(db, _installation, project)
                db.commit()
                _prepared.add(schema)
        db.execute(sql.SQL('SET search_path TO {}, public').format(sql.Identifier(schema)))
        db.commit()
        return BusinessConnection(db)
    except Exception:
        db.close()
        raise


def appearance_connect(path, encoder, dimension):
    """One PostgreSQL namespace per project/path and encoder; import SQLite once.

    Matching remains in RAM. The caller serializes use of this background writer.
    Original SQLite files are retained as backups, never opened for new writes.
    """
    if _root is None or not Path(path).resolve().is_relative_to(_root):
        return None
    from psycopg import sql
    from identity.memory import ESQUEMA
    namespace = 'aero_m_' + hashlib.sha256(
        (_installation + ':' + key_for(path) + ':' + encoder + ':' + str(dimension)).encode()
    ).hexdigest()[:24]
    db = connect_db()
    try:
        db.execute('SELECT pg_advisory_xact_lock(hashtextextended(%s,0))', (namespace,))
        db.execute(sql.SQL('CREATE SCHEMA IF NOT EXISTS {}').format(sql.Identifier(namespace)))
        db.execute(sql.SQL('SET search_path TO {}, public').format(sql.Identifier(namespace)))
        con = BusinessConnection(db)
        con.executescript(ESQUEMA)
        meta = dict(con.execute('SELECT clave,valor FROM appearance_meta').fetchall())
        if not meta.get('migration_complete'):
            if Path(path).exists():
                with closing(sqlite3.connect(Path(path).resolve().as_uri() + '?mode=ro', uri=True)) as old:
                    previous = dict(old.execute('SELECT clave,valor FROM appearance_meta').fetchall())
                    if previous.get('encoder') == encoder and previous.get('dimension') == str(dimension):
                        for table, placeholders in [('appearance_people','?,?,?,?,?,?,?'), ('appearance_views','?,?,?,?,?'), ('appearance_meta','?,?')]:
                            con.executemany(f'INSERT OR IGNORE INTO {table} VALUES ({placeholders})', old.execute(f'SELECT * FROM {table}').fetchall())
            con.execute('INSERT OR REPLACE INTO appearance_meta VALUES (?,?)', ('migration_complete','1'))
        db.commit()
        return con
    except Exception:
        db.close()
        raise
